import { Test, TestingModule } from '@nestjs/testing';
import { QuoteV2Controller } from './quote.controller';
import { QuoteServiceV2 } from '../../services/quote/quote.service';
import { SfdcQuoteService } from '../../../../backend/sfdc/services/sfdc-quote/sfdc-quote.service';
import { FirestoreService } from '../../../../backend/google/firestore/firestore.service';
import { CacheService } from '../../../../core/cache/cache.service';
import { LoggerService } from '../../../../core/logger/logger.service';
import { UserService } from '../../../../myuss/services/user/user.service';
import { QuoteService } from '../../../../myuss/services/quote/quote.service';
import { AccountsService } from '../../../../myuss/services/accounts/accounts.service';
jest.mock('../../../../core/logger/logger.service');
jest.mock('../../../../core/cache/cache.service');

describe('QuoteV2Controller', () => {
  let controller: QuoteV2Controller;

  let mockQuoteServiceV2 = {
    getQuoteHtmlModel: jest.fn(),
    getQuoteDetailsById:jest.fn()
  };

  let mockSfdcQuoteService = {
    getQuoteDetailsById: jest.fn(),
  };

  let mockFirestoreService = {
    getDocument: jest.fn(),
  };

  let mockCacheService = {
    get: jest.fn(),
    set: jest.fn(),
    delete: jest.fn(),
    reset: jest.fn(),
  };

  let mockLoggerService = {
    debug: jest.fn(),
    log: jest.fn(),
    warn: jest.fn(),
    info: jest.fn(),
    error: jest.fn(),
  };
  let mockUserService = {
    requestEmailVerification: jest.fn(),
    fetchUsersDetails: jest.fn(),
    fetchProfile: jest.fn(),
    fetchAccountDetails: jest.fn(),
    createUser: jest.fn(),
    updateUser: jest.fn(),
    updateCache: jest.fn(),
    hasAccessToAccount: jest.fn(),
    clearCache: jest.fn(),
    getCacheKeys: jest.fn(),
    fetchQuoteIds: jest.fn(),
    fetchContractIds: jest.fn(),
    fetchContactAndUssPortalUser: jest.fn(),
    updateLastLogin: jest.fn(),
    addUserContactForAccount: jest.fn(),
    fetchUserContactListForAccount: jest.fn(),
    editUserContactForAccount: jest.fn(),
    createAuth0Users: jest.fn(),
    createAuth0User: jest.fn(),
    createSuccessResponse: jest.fn(),
    deleteUser: jest.fn(),
  };

  let mockQuoteService = {
    createInitialQuote: jest.fn(),
    quoteRequestData: jest.fn(),
    addressDetailsData: jest.fn(),
    createOpportunityData: jest.fn(),
    addProductAndSave: jest.fn(),
    calculateAndSavePriceAndTax: jest.fn(),
    calculateAndSavePriceAndTaxCPQ: jest.fn(),
    calculateAndSavePriceAndTaxStandalone: jest.fn(),
    getQuoteHtmlModel: jest.fn(),
    generateSortOrder: jest.fn(),
    createQuoteLinesModel: jest.fn(),
    createShortTermQuoteLineIfNeeded: jest.fn(),
    createQuoteModelFromBundles: jest.fn(),
    createAndSaveQuoteDocument: jest.fn(),
    getDocumentId: jest.fn(),
    updateSiteDetails: jest.fn(),
    deleteQuotedJobSite: jest.fn(),
    updateQuoteStatus: jest.fn(),
    updateBillingAddress: jest.fn(),
    savePaymentMethodIdToFirestore: jest.fn(),
    saveAccoutwiseIdsToFirestore: jest.fn(),
    updateAccoutwiseIdsToFirestore: jest.fn(),
    confirmQuote: jest.fn(),
    getBundleFromProductDetails: jest.fn(),
    mapProductIdToBundleProduct: jest.fn(),
    getQuoteDocumentBody: jest.fn(),
    approveQuote: jest.fn(),
    calculateTaxForQuoteModel: jest.fn(),
    getQuoteDetailsById: jest.fn(),
    getQuoteBillingContact: jest.fn(),
    getQuoteSecondaryContact: jest.fn(),
    getQuoteBillingAddress: jest.fn(),
    getQuoteSiteContact: jest.fn(),
    getQuoteSiteDetails: jest.fn(),
    getQuoteLatestDocumentVersion: jest.fn(),
    getQuoteProductsDetails: jest.fn(),
  };

  let mockAccountsService = {
    getAccount: jest.fn(),
    getContacts: jest.fn(),
    checkDuplicateAddress: jest.fn(),
    fetchDrafts: jest.fn(),
    fetchArchivedDrafts: jest.fn(),
    fetchSuspendedDrafts: jest.fn(),
    trackUserActions: jest.fn(),
    checkQuoteIdInAccount: jest.fn(),
    fetchAccountNumber: jest.fn(),
    checkContractIdInAccount: jest.fn(),
    fetchAllDashboardDetails: jest.fn(),
  };

  let getSfdcQuoteDetailsResponse = {
    attributes: {
      type: 'SBQQ__Quote__c',
      url: '/services/data/v58.0/sobjects/SBQQ__Quote__c/a6OVA0000006Izx2AE',
    },
    Id: 'a6OVA0000006Izx2AE',
    Name: 'Q-521314',
    Quote_Name__c: 'MyUSS Quote 2024-08-22T11:51:55.563Z',
    SBQQ__StartDate__c: '2024-09-18',
    Site_Complete__c: true,
    Billing_Complete__c: false,
    isCheckPaymentMethod__c: false,
    SBQQ__EndDate__c: '2049-12-31',
    SBQQ__PriceBook__c: '01s1N000007nDwhQAE',
    BillToContact__c: null,
    PrimarySiteContact__c: null,
    SBQQ__PrimaryContact__c: '0038I00000fn3IZQAY',
    SecondaryBillToContact__c: null,
    Ship_To_Contact__c: null,
    AutoPay__c: true,
    Payment_Method_Id__c: null,
    Payment_Mode__c: 'creditDebit',
    SBQQ__Status__c: 'Approved',
    SBQQ__Ordered__c: false,
    BillCycleDay__c: null,
    Charge_Type__c: 'Recurring',
    EEC_Percent__c: 10,
    ESF_Percent__c: 1,
    Fuel_Surcharge_Percent__c: 14.9,
    LastBillingDate__c: null,
    Enable_Server_Side_Pricing_Calculation__c: false,
    AVA_SFCPQ__Entity_Use_Code__c: null,
    AvaTax_Company_Code__c: 'USNE',
    AVA_SFCPQ__Is_Seller_Importer_Of_Record__c: false,
    AVA_SFCPQ__SalesTaxAmount__c: 7.5,
    AVA_SFCPQ__AvaTaxMessage__c: 'Tax Amount is Outdated',
    Duration__c: '1-3 Months',
    Recalculate__c: false,
    SBQQ_ExpirationDateFormatted__c: '09-21-24',
    Quote_Date__c: '2024-08-22',
    Recurring_Subtotal__c: 1499.53,
    Recurring_Tax__c: 9.37,
    Recurring_Total__c: 1508.9,
    One_Time_Subtotal__c: 226.66,
    One_Time_Tax__c: 0,
    One_Time_Total__c: 226.66,
    FirstInvoice_GrossAmount_Disp__c: 1735.56,
    Current_Date_Formatted__c: '08-23-24',
    Reference_Number__c: '521314',
    SBQQ__Account__r: {
      attributes: {
        type: 'Account',
        url: '/services/data/v58.0/sobjects/Account/0018I00000jIg0sQAC',
      },
      Id: '0018I00000jIg0sQAC',
      USF_Account_Number__c: 'ACT-01640742',
      Parent_Account_Number__c: 'ACT-01640742',
      Name: 'SANJIV-Account',
      Owner: {
        attributes: {
          type: 'User',
          url: '/services/data/v58.0/sobjects/User/0058I000002oBmXQAU',
        },
        Id: '0058I000002oBmXQAU',
        FirstName: 'MyUSS',
        LastName: 'System User',
        Title: null,
        Email: 'myussadmin@unitedsiteservices.com',
        Phone: null,
        Username: 'myuss@unitedsiteservices.com.devminor',
      },
    },
    SBQQ__PrimaryContact__r: {
      attributes: {
        type: 'Contact',
        url: '/services/data/v58.0/sobjects/Contact/0038I00000fn3IZQAY',
      },
      Id: '0038I00000fn3IZQAY',
      Phone: '+918380096983',
      Email: 'sanjivbshinde@gmail.com',
      FirstName: 'Sanjiv b',
      LastName: 'Shinde',
    },
    PrimarySiteContact__r: null,
    SecondaryBillToContact__r: null,
    SBQQ__SalesRep__r: {
      attributes: {
        type: 'User',
        url: '/services/data/v58.0/sobjects/User/0058I000002oBmXQAU',
      },
      Id: '0058I000002oBmXQAU',
      FirstName: 'MyUSS',
      LastName: 'System User',
      Email: 'myussadmin@unitedsiteservices.com',
      Title: null,
    },
    Legal_Entity__c: 'United Site Services Northeast, Inc.',
    Shipping_Address__r: {
      attributes: {
        type: 'USF_Address__c',
        url: '/services/data/v58.0/sobjects/USF_Address__c/a8x8I000000CoKpQAK',
      },
      Id: 'a8x8I000000CoKpQAK',
      USF_Account__c: '0018I00000jIg0sQAC',
      Name: '136 Pleasant Street - Brookline - MA',
      NF_Parent_USF_Address__c: null,
      USF_Street__c: '136 Pleasant Street',
      USF_City__c: 'Brookline',
      USF_State__c: 'MA',
      USF_Zip_Code__c: '02446',
      USF_Country__c: 'US',
      Address_Latitude_Longitude__Latitude__s: 42.34714,
      Address_Latitude_Longitude__Longitude__s: -71.11867,
      Is_Primary__c: false,
      USF_Ship_To_Address__c: true,
      USF_Bill_To_Address__c: false,
      NF_Is_Parent__c: true,
      Address_Validated__c: true,
      GeoCode_Accuracy__c: 'Address',
      Site_Name__c: '136 Pleasant Street - Brookline - MA',
      NF_Site_Hours_Start_Time__c: '09:00:00.125Z',
      NF_Site_Hours_End_Time__c: '21:00:00.125Z',
      NF_Arrival_Start_Time__c: null,
      NF_Arrival_End_Time__c: null,
      NF_Gate_Code__c: 'Gate 300',
      NF_Access_instructions__c: null,
      NF_Key_Instructions__c: null,
      NF_Other_Instructions__c: 'Bong',
      NF_Placement__c: '090',
      NF_Background_Check__c: true,
      NF_Clearance_Required__c: true,
      Additional_Information__c: 'PL Note12',
      NF_Site_Contact__c: '0038I00000fn3IZQAY',
      NF_Secondary_Site_Contact__c: null,
      NF_Ship_To_Contact__c: '0038I00000fn3IZQAY',
    },
    Bill_To_Address__r: null,
    SBQQ__Opportunity2__r: {
      attributes: {
        type: 'Opportunity',
        url: '/services/data/v58.0/sobjects/Opportunity/006VA000006M3iJYAS',
      },
      USF_Project__c: null,
      USF_Project__r: null,
    },
    CreatedDate: '2024-08-22T11:52:14.000+0000',
    SBQQ__ExpirationDate__c: '2024-09-21',
    Estimated_End_Date__c: '2024-10-23',
    Purchase_Order__r: null,
    SBQQ__LineItems__r: {
      totalSize: 12,
      done: true,
      records: [
        {
          attributes: {
            type: 'SBQQ__QuoteLine__c',
            url: '/services/data/v58.0/sobjects/SBQQ__QuoteLine__c/a6KVA000000NjSf2AK',
          },
          Id: 'a6KVA000000NjSf2AK',
          SBQQ__Quote__c: 'a6OVA0000006Izx2AE',
          SBQQ__Number__c: 1,
          Name: 'QL-8397054',
          Product_Name__c: 'Hand Cleaning Bundle',
          Sort_Order__c: '00000000100000',
          QuantityUnitOfMeasure__c: null,
          SBQQ__Taxable__c: true,
          SBQQ__Quantity__c: 1,
          IS2PContractedPrice__c: false,
          SBQQ__SpecialPriceType__c: null,
          SBQQ__ListPrice__c: 0,
          Floor_Price__c: 0,
          SBQQ__UnitCost__c: null,
          SBQQ__NetPrice__c: 0,
          SBQQ__CustomerPrice__c: 0,
          Price_Override__c: 0,
          SBQQ__EffectiveStartDate__c: '2024-09-18',
          Total_Sales_Tax_Amount__c: null,
          Apply_Houston_Franchise_Fee__c: false,
          Houston_Franchise_Fees_Percent__c: 0,
          Houston_Franchise_Fee_Per_Unit__c: 0,
          Houston_Franchise_Fees__c: 0,
          Apply_Fuel_Surcharge__c: false,
          Fuel_Surcharge_Percent__c: 0,
          Fuel_Surcharge_Amount__c: 0,
          Fuel_Surcharge_Per_Unit__c: 0,
          Product_Type__c: 'Bundle',
          SBQQ__RequiredBy__c: null,
          USS_Net__c: 0,
          SBQQ__ChargeType__c: 'Recurring',
          EEC_Charge__c: 0,
          ESF_Charge__c: 0,
          SBQQ__StartDate__c: '2024-09-18',
          SBQQ__EndDate__c: '2049-12-31',
          SBQQ__PricebookEntryId__c: '01u3m00000O2tSEAAZ',
          SBQQ__SubscriptionTerm__c: null,
          SBQQ__ProductSubscriptionType__c: 'Renewable',
          SBQQ__ProrateMultiplier__c: 303.46027397260275,
          SBQQ__SubscriptionPricing__c: 'Fixed Price',
          SBQQ__SubscriptionType__c: 'Renewable',
          SBQQ__DefaultSubscriptionTerm__c: 1,
          SBQQ__ProductCode__c: '120-0000',
          AVA_SFCPQ__Location_Code__c: null,
          USF_Address__c: 'a8x8I000000CoKpQAK',
          SBQQ__TaxCode__c: null,
          Ship_From_Street__c: '31 East Belcher Rd',
          Ship_From_City__c: 'Foxboro',
          Ship_From_State__c: 'Massachusetts',
          Ship_From_Zipcode__c: '02035',
          AVA_SFCPQ__TaxAmount__c: 0,
          ESF_Percent__c: 0,
          EEC_Percent__c: 0,
          SBQQ__Product__c: '01t3m00000PPH5RAAX',
          SBQQ__Product__r: {
            attributes: {
              type: 'Product2',
              url: '/services/data/v58.0/sobjects/Product2/01t3m00000PPH5RAAX',
            },
            Id: '01t3m00000PPH5RAAX',
            Name: 'Hand Cleaning Bundle',
            ProductCode: '120-0000',
            Description: 'Hand Cleaning Bundle Configuration',
            Asset_Summary__c: null,
            Apply_Fuel_Surcharge__c: false,
            ApplyEnhancedSafetyFee__c: false,
            Apply_EEC__c: false,
          },
          SBQQ__ProductOption__r: null,
        },
        {
          attributes: {
            type: 'SBQQ__QuoteLine__c',
            url: '/services/data/v58.0/sobjects/SBQQ__QuoteLine__c/a6KVA000000NjSg2AK',
          },
          Id: 'a6KVA000000NjSg2AK',
          SBQQ__Quote__c: 'a6OVA0000006Izx2AE',
          SBQQ__Number__c: 6,
          Name: 'QL-8397055',
          Product_Name__c: 'Restroom Bundle',
          Sort_Order__c: '00000000600000',
          QuantityUnitOfMeasure__c: null,
          SBQQ__Taxable__c: true,
          SBQQ__Quantity__c: 2,
          IS2PContractedPrice__c: false,
          SBQQ__SpecialPriceType__c: null,
          SBQQ__ListPrice__c: 0,
          Floor_Price__c: 0,
          SBQQ__UnitCost__c: null,
          SBQQ__NetPrice__c: 0,
          SBQQ__CustomerPrice__c: 0,
          Price_Override__c: 0,
          SBQQ__EffectiveStartDate__c: '2024-09-18',
          Total_Sales_Tax_Amount__c: null,
          Apply_Houston_Franchise_Fee__c: false,
          Houston_Franchise_Fees_Percent__c: 0,
          Houston_Franchise_Fee_Per_Unit__c: 0,
          Houston_Franchise_Fees__c: 0,
          Apply_Fuel_Surcharge__c: false,
          Fuel_Surcharge_Percent__c: 0,
          Fuel_Surcharge_Amount__c: 0,
          Fuel_Surcharge_Per_Unit__c: 0,
          Product_Type__c: 'Bundle',
          SBQQ__RequiredBy__c: null,
          USS_Net__c: 0,
          SBQQ__ChargeType__c: 'Recurring',
          EEC_Charge__c: 0,
          ESF_Charge__c: 0,
          SBQQ__StartDate__c: '2024-09-18',
          SBQQ__EndDate__c: '2049-12-31',
          SBQQ__PricebookEntryId__c: '01u3m00000O2tSBAAZ',
          SBQQ__SubscriptionTerm__c: null,
          SBQQ__ProductSubscriptionType__c: 'Renewable',
          SBQQ__ProrateMultiplier__c: 303.46027397260275,
          SBQQ__SubscriptionPricing__c: 'Fixed Price',
          SBQQ__SubscriptionType__c: 'Renewable',
          SBQQ__DefaultSubscriptionTerm__c: 1,
          SBQQ__ProductCode__c: '110-0000',
          AVA_SFCPQ__Location_Code__c: null,
          USF_Address__c: 'a8x8I000000CoKpQAK',
          SBQQ__TaxCode__c: null,
          Ship_From_Street__c: '31 East Belcher Rd',
          Ship_From_City__c: 'Foxboro',
          Ship_From_State__c: 'Massachusetts',
          Ship_From_Zipcode__c: '02035',
          AVA_SFCPQ__TaxAmount__c: 0,
          ESF_Percent__c: 0,
          EEC_Percent__c: 0,
          SBQQ__Product__c: '01t3m00000PPH5MAAX',
          SBQQ__Product__r: {
            attributes: {
              type: 'Product2',
              url: '/services/data/v58.0/sobjects/Product2/01t3m00000PPH5MAAX',
            },
            Id: '01t3m00000PPH5MAAX',
            Name: 'Restroom Bundle',
            ProductCode: '110-0000',
            Description: 'Restroom Bundle Configuration',
            Asset_Summary__c: null,
            Apply_Fuel_Surcharge__c: false,
            ApplyEnhancedSafetyFee__c: false,
            Apply_EEC__c: false,
          },
          SBQQ__ProductOption__r: null,
        },
        {
          attributes: {
            type: 'SBQQ__QuoteLine__c',
            url: '/services/data/v58.0/sobjects/SBQQ__QuoteLine__c/a6KVA000000NjSh2AK',
          },
          Id: 'a6KVA000000NjSh2AK',
          SBQQ__Quote__c: 'a6OVA0000006Izx2AE',
          SBQQ__Number__c: 11,
          Name: 'QL-8397056',
          Product_Name__c: 'Pick Sani Standard',
          Sort_Order__c: '50000000000000',
          QuantityUnitOfMeasure__c: 'Each',
          SBQQ__Taxable__c: false,
          SBQQ__Quantity__c: 1,
          IS2PContractedPrice__c: false,
          SBQQ__SpecialPriceType__c: null,
          SBQQ__ListPrice__c: 0,
          Floor_Price__c: 45,
          SBQQ__UnitCost__c: null,
          SBQQ__NetPrice__c: 0,
          SBQQ__CustomerPrice__c: 0,
          Price_Override__c: 45,
          SBQQ__EffectiveStartDate__c: '2024-09-18',
          Total_Sales_Tax_Amount__c: 0,
          Apply_Houston_Franchise_Fee__c: true,
          Houston_Franchise_Fees_Percent__c: 0,
          Houston_Franchise_Fee_Per_Unit__c: 0,
          Houston_Franchise_Fees__c: 0,
          Apply_Fuel_Surcharge__c: true,
          Fuel_Surcharge_Percent__c: 14.9,
          Fuel_Surcharge_Amount__c: 6.71,
          Fuel_Surcharge_Per_Unit__c: 6.71,
          Product_Type__c: 'P n D',
          SBQQ__RequiredBy__c: null,
          USS_Net__c: 45,
          SBQQ__ChargeType__c: 'One-Time',
          EEC_Charge__c: 4.5,
          ESF_Charge__c: 0.45,
          SBQQ__StartDate__c: '2024-09-18',
          SBQQ__EndDate__c: '2049-12-31',
          SBQQ__PricebookEntryId__c: '01u3m00000O2tWOAAZ',
          SBQQ__SubscriptionTerm__c: null,
          SBQQ__ProductSubscriptionType__c: 'One-time',
          SBQQ__ProrateMultiplier__c: 303.46027397260275,
          SBQQ__SubscriptionPricing__c: 'Fixed Price',
          SBQQ__SubscriptionType__c: 'One-time',
          SBQQ__DefaultSubscriptionTerm__c: 1,
          SBQQ__ProductCode__c: '113-3005',
          AVA_SFCPQ__Location_Code__c: null,
          USF_Address__c: 'a8x8I000000CoKpQAK',
          SBQQ__TaxCode__c: 'FR010000',
          Ship_From_Street__c: '31 East Belcher Rd',
          Ship_From_City__c: 'Foxboro',
          Ship_From_State__c: 'Massachusetts',
          Ship_From_Zipcode__c: '02035',
          AVA_SFCPQ__TaxAmount__c: 0,
          ESF_Percent__c: 1,
          EEC_Percent__c: 10,
          SBQQ__Product__c: '01t3m00000POgwyAAD',
          SBQQ__Product__r: {
            attributes: {
              type: 'Product2',
              url: '/services/data/v58.0/sobjects/Product2/01t3m00000POgwyAAD',
            },
            Id: '01t3m00000POgwyAAD',
            Name: 'Pick Sani Standard',
            ProductCode: '113-3005',
            Description: 'Pickup Sanitation - Standard',
            Asset_Summary__c: 'Cart-level P&D Sanitation',
            Apply_Fuel_Surcharge__c: true,
            ApplyEnhancedSafetyFee__c: true,
            Apply_EEC__c: true,
          },
          SBQQ__ProductOption__r: null,
        },
        {
          attributes: {
            type: 'SBQQ__QuoteLine__c',
            url: '/services/data/v58.0/sobjects/SBQQ__QuoteLine__c/a6KVA000000NjSi2AK',
          },
          Id: 'a6KVA000000NjSi2AK',
          SBQQ__Quote__c: 'a6OVA0000006Izx2AE',
          SBQQ__Number__c: 12,
          Name: 'QL-8397057',
          Product_Name__c: 'Del Sani Standard',
          Sort_Order__c: '50000000000000',
          QuantityUnitOfMeasure__c: 'Each',
          SBQQ__Taxable__c: false,
          SBQQ__Quantity__c: 1,
          IS2PContractedPrice__c: false,
          SBQQ__SpecialPriceType__c: null,
          SBQQ__ListPrice__c: 60,
          Floor_Price__c: 45,
          SBQQ__UnitCost__c: null,
          SBQQ__NetPrice__c: 18207.62,
          SBQQ__CustomerPrice__c: 18207.62,
          Price_Override__c: 45,
          SBQQ__EffectiveStartDate__c: '2024-09-18',
          Total_Sales_Tax_Amount__c: 0,
          Apply_Houston_Franchise_Fee__c: true,
          Houston_Franchise_Fees_Percent__c: 0,
          Houston_Franchise_Fee_Per_Unit__c: 0,
          Houston_Franchise_Fees__c: 0,
          Apply_Fuel_Surcharge__c: true,
          Fuel_Surcharge_Percent__c: 14.9,
          Fuel_Surcharge_Amount__c: 6.71,
          Fuel_Surcharge_Per_Unit__c: 6.71,
          Product_Type__c: 'P n D',
          SBQQ__RequiredBy__c: null,
          USS_Net__c: 45,
          SBQQ__ChargeType__c: 'One-Time',
          EEC_Charge__c: 4.5,
          ESF_Charge__c: 0.45,
          SBQQ__StartDate__c: '2024-09-18',
          SBQQ__EndDate__c: '2049-12-31',
          SBQQ__PricebookEntryId__c: '01u3m00000O2tXOAAZ',
          SBQQ__SubscriptionTerm__c: null,
          SBQQ__ProductSubscriptionType__c: 'One-time',
          SBQQ__ProrateMultiplier__c: 303.46027397260275,
          SBQQ__SubscriptionPricing__c: 'Fixed Price',
          SBQQ__SubscriptionType__c: 'One-time',
          SBQQ__DefaultSubscriptionTerm__c: 1,
          SBQQ__ProductCode__c: '113-3001',
          AVA_SFCPQ__Location_Code__c: null,
          USF_Address__c: 'a8x8I000000CoKpQAK',
          SBQQ__TaxCode__c: 'FR010000',
          Ship_From_Street__c: '31 East Belcher Rd',
          Ship_From_City__c: 'Foxboro',
          Ship_From_State__c: 'Massachusetts',
          Ship_From_Zipcode__c: '02035',
          AVA_SFCPQ__TaxAmount__c: 0,
          ESF_Percent__c: 1,
          EEC_Percent__c: 10,
          SBQQ__Product__c: '01t3m00000POgwjAAD',
          SBQQ__Product__r: {
            attributes: {
              type: 'Product2',
              url: '/services/data/v58.0/sobjects/Product2/01t3m00000POgwjAAD',
            },
            Id: '01t3m00000POgwjAAD',
            Name: 'Del Sani Standard',
            ProductCode: '113-3001',
            Description: 'Delivery Sanitation - Standard',
            Asset_Summary__c: 'Cart-level P&D Sanitation',
            Apply_Fuel_Surcharge__c: true,
            ApplyEnhancedSafetyFee__c: true,
            Apply_EEC__c: true,
          },
          SBQQ__ProductOption__r: null,
        },
        {
          attributes: {
            type: 'SBQQ__QuoteLine__c',
            url: '/services/data/v58.0/sobjects/SBQQ__QuoteLine__c/a6KVA000000NjSj2AK',
          },
          Id: 'a6KVA000000NjSj2AK',
          SBQQ__Quote__c: 'a6OVA0000006Izx2AE',
          SBQQ__Number__c: 2,
          Name: 'QL-8397058',
          Product_Name__c: '2 Stn Hand Sink',
          Sort_Order__c: '00000000200010',
          QuantityUnitOfMeasure__c: 'Each',
          SBQQ__Taxable__c: true,
          SBQQ__Quantity__c: 1,
          IS2PContractedPrice__c: false,
          SBQQ__SpecialPriceType__c: null,
          SBQQ__ListPrice__c: 20,
          Floor_Price__c: 40,
          SBQQ__UnitCost__c: null,
          SBQQ__NetPrice__c: 6069.21,
          SBQQ__CustomerPrice__c: 6069.21,
          Price_Override__c: 40,
          SBQQ__EffectiveStartDate__c: '2024-09-18',
          Total_Sales_Tax_Amount__c: 3.12,
          Apply_Houston_Franchise_Fee__c: true,
          Houston_Franchise_Fees_Percent__c: 0,
          Houston_Franchise_Fee_Per_Unit__c: 0,
          Houston_Franchise_Fees__c: 0,
          Apply_Fuel_Surcharge__c: true,
          Fuel_Surcharge_Percent__c: 14.9,
          Fuel_Surcharge_Amount__c: 5.96,
          Fuel_Surcharge_Per_Unit__c: 5.96,
          Product_Type__c: 'Asset',
          SBQQ__RequiredBy__c: 'a6KVA000000NjSf2AK',
          USS_Net__c: 40,
          SBQQ__ChargeType__c: 'Recurring',
          EEC_Charge__c: 4,
          ESF_Charge__c: 0,
          SBQQ__StartDate__c: '2024-09-18',
          SBQQ__EndDate__c: '2049-12-31',
          SBQQ__PricebookEntryId__c: '01u3m00000O2tTSAAZ',
          SBQQ__SubscriptionTerm__c: null,
          SBQQ__ProductSubscriptionType__c: 'Renewable',
          SBQQ__ProrateMultiplier__c: 303.46027397260275,
          SBQQ__SubscriptionPricing__c: 'Fixed Price',
          SBQQ__SubscriptionType__c: 'Renewable',
          SBQQ__DefaultSubscriptionTerm__c: 1,
          SBQQ__ProductCode__c: '121-1102',
          AVA_SFCPQ__Location_Code__c: null,
          USF_Address__c: 'a8x8I000000CoKpQAK',
          SBQQ__TaxCode__c: 'SANIRENT',
          Ship_From_Street__c: '31 East Belcher Rd',
          Ship_From_City__c: 'Foxboro',
          Ship_From_State__c: 'Massachusetts',
          Ship_From_Zipcode__c: '02035',
          AVA_SFCPQ__TaxAmount__c: 2.5,
          ESF_Percent__c: 0,
          EEC_Percent__c: 10,
          SBQQ__Product__c: '01t3m00000NTiuFAAT',
          SBQQ__Product__r: {
            attributes: {
              type: 'Product2',
              url: '/services/data/v58.0/sobjects/Product2/01t3m00000NTiuFAAT',
            },
            Id: '01t3m00000NTiuFAAT',
            Name: '2 Stn Hand Sink',
            ProductCode: '121-1102',
            Description: '2 Station Hand Wash Sink',
            Asset_Summary__c: '2 Station Hand Cleaning',
            Apply_Fuel_Surcharge__c: true,
            ApplyEnhancedSafetyFee__c: false,
            Apply_EEC__c: true,
          },
          SBQQ__ProductOption__r: {
            attributes: {
              type: 'SBQQ__ProductOption__c',
              url: '/services/data/v58.0/sobjects/SBQQ__ProductOption__c/a6D8I0000008aKyUAI',
            },
            Id: 'a6D8I0000008aKyUAI',
            SBQQ__Number__c: 10,
          },
        },
        {
          attributes: {
            type: 'SBQQ__QuoteLine__c',
            url: '/services/data/v58.0/sobjects/SBQQ__QuoteLine__c/a6KVA000000NjSk2AK',
          },
          Id: 'a6KVA000000NjSk2AK',
          SBQQ__Quote__c: 'a6OVA0000006Izx2AE',
          SBQQ__Number__c: 3,
          Name: 'QL-8397059',
          Product_Name__c: '1 Svc 2 Days Wk',
          Sort_Order__c: '00000000300020',
          QuantityUnitOfMeasure__c: 'Each',
          SBQQ__Taxable__c: false,
          SBQQ__Quantity__c: 1,
          IS2PContractedPrice__c: false,
          SBQQ__SpecialPriceType__c: null,
          SBQQ__ListPrice__c: 160,
          Floor_Price__c: 314,
          SBQQ__UnitCost__c: null,
          SBQQ__NetPrice__c: 48553.64,
          SBQQ__CustomerPrice__c: 48553.64,
          Price_Override__c: 370,
          SBQQ__EffectiveStartDate__c: '2024-09-18',
          Total_Sales_Tax_Amount__c: 0,
          Apply_Houston_Franchise_Fee__c: true,
          Houston_Franchise_Fees_Percent__c: 0,
          Houston_Franchise_Fee_Per_Unit__c: 0,
          Houston_Franchise_Fees__c: 0,
          Apply_Fuel_Surcharge__c: true,
          Fuel_Surcharge_Percent__c: 14.9,
          Fuel_Surcharge_Amount__c: 55.13,
          Fuel_Surcharge_Per_Unit__c: 55.13,
          Product_Type__c: 'Service',
          SBQQ__RequiredBy__c: 'a6KVA000000NjSf2AK',
          USS_Net__c: 370,
          SBQQ__ChargeType__c: 'Recurring',
          EEC_Charge__c: 37,
          ESF_Charge__c: 3.7,
          SBQQ__StartDate__c: '2024-09-18',
          SBQQ__EndDate__c: '2049-12-31',
          SBQQ__PricebookEntryId__c: '01u3m00000O2tYVAAZ',
          SBQQ__SubscriptionTerm__c: null,
          SBQQ__ProductSubscriptionType__c: 'Renewable',
          SBQQ__ProrateMultiplier__c: 303.46027397260275,
          SBQQ__SubscriptionPricing__c: 'Fixed Price',
          SBQQ__SubscriptionType__c: 'Renewable',
          SBQQ__DefaultSubscriptionTerm__c: 1,
          SBQQ__ProductCode__c: '122-2002',
          AVA_SFCPQ__Location_Code__c: null,
          USF_Address__c: 'a8x8I000000CoKpQAK',
          SBQQ__TaxCode__c: 'SANISERV',
          Ship_From_Street__c: '31 East Belcher Rd',
          Ship_From_City__c: 'Foxboro',
          Ship_From_State__c: 'Massachusetts',
          Ship_From_Zipcode__c: '02035',
          AVA_SFCPQ__TaxAmount__c: 0,
          ESF_Percent__c: 1,
          EEC_Percent__c: 10,
          SBQQ__Product__c: '01t3m00000POgyQAAT',
          SBQQ__Product__r: {
            attributes: {
              type: 'Product2',
              url: '/services/data/v58.0/sobjects/Product2/01t3m00000POgyQAAT',
            },
            Id: '01t3m00000POgyQAAT',
            Name: '1 Svc 2 Days Wk',
            ProductCode: '122-2002',
            Description: '1 Service 2 Days per Week',
            Asset_Summary__c: 'Group A Sanitation',
            Apply_Fuel_Surcharge__c: true,
            ApplyEnhancedSafetyFee__c: true,
            Apply_EEC__c: true,
          },
          SBQQ__ProductOption__r: {
            attributes: {
              type: 'SBQQ__ProductOption__c',
              url: '/services/data/v58.0/sobjects/SBQQ__ProductOption__c/a6D8I0000008aUwUAI',
            },
            Id: 'a6D8I0000008aUwUAI',
            SBQQ__Number__c: 20,
          },
        },
        {
          attributes: {
            type: 'SBQQ__QuoteLine__c',
            url: '/services/data/v58.0/sobjects/SBQQ__QuoteLine__c/a6KVA000000NjSl2AK',
          },
          Id: 'a6KVA000000NjSl2AK',
          SBQQ__Quote__c: 'a6OVA0000006Izx2AE',
          SBQQ__Number__c: 4,
          Name: 'QL-8397060',
          Product_Name__c: 'Del Hand per Unit',
          Sort_Order__c: '00000000400001',
          QuantityUnitOfMeasure__c: 'Each',
          SBQQ__Taxable__c: false,
          SBQQ__Quantity__c: 1,
          IS2PContractedPrice__c: false,
          SBQQ__SpecialPriceType__c: null,
          SBQQ__ListPrice__c: 5,
          Floor_Price__c: 15,
          SBQQ__UnitCost__c: null,
          SBQQ__NetPrice__c: 1517.3,
          SBQQ__CustomerPrice__c: 1517.3,
          Price_Override__c: 15,
          SBQQ__EffectiveStartDate__c: '2024-09-18',
          Total_Sales_Tax_Amount__c: 0,
          Apply_Houston_Franchise_Fee__c: true,
          Houston_Franchise_Fees_Percent__c: 0,
          Houston_Franchise_Fee_Per_Unit__c: 0,
          Houston_Franchise_Fees__c: 0,
          Apply_Fuel_Surcharge__c: true,
          Fuel_Surcharge_Percent__c: 14.9,
          Fuel_Surcharge_Amount__c: 2.24,
          Fuel_Surcharge_Per_Unit__c: 2.24,
          Product_Type__c: 'P n D',
          SBQQ__RequiredBy__c: 'a6KVA000000NjSf2AK',
          USS_Net__c: 15,
          SBQQ__ChargeType__c: 'One-Time',
          EEC_Charge__c: 1.5,
          ESF_Charge__c: 0.15,
          SBQQ__StartDate__c: '2024-09-18',
          SBQQ__EndDate__c: '2049-12-31',
          SBQQ__PricebookEntryId__c: '01u3m00000O2tWWAAZ',
          SBQQ__SubscriptionTerm__c: null,
          SBQQ__ProductSubscriptionType__c: 'One-time',
          SBQQ__ProrateMultiplier__c: 303.46027397260275,
          SBQQ__SubscriptionPricing__c: 'Fixed Price',
          SBQQ__SubscriptionType__c: 'One-time',
          SBQQ__DefaultSubscriptionTerm__c: 1,
          SBQQ__ProductCode__c: '123-3009',
          AVA_SFCPQ__Location_Code__c: null,
          USF_Address__c: 'a8x8I000000CoKpQAK',
          SBQQ__TaxCode__c: 'FR010000',
          Ship_From_Street__c: '31 East Belcher Rd',
          Ship_From_City__c: 'Foxboro',
          Ship_From_State__c: 'Massachusetts',
          Ship_From_Zipcode__c: '02035',
          AVA_SFCPQ__TaxAmount__c: 0,
          ESF_Percent__c: 1,
          EEC_Percent__c: 10,
          SBQQ__Product__c: '01t3m00000POh0HAAT',
          SBQQ__Product__r: {
            attributes: {
              type: 'Product2',
              url: '/services/data/v58.0/sobjects/Product2/01t3m00000POh0HAAT',
            },
            Id: '01t3m00000POh0HAAT',
            Name: 'Del Hand per Unit',
            ProductCode: '123-3009',
            Description: 'Delivery Hand Cleaning - Per Unit Charge',
            Asset_Summary__c: 'Non-fees Sanitation',
            Apply_Fuel_Surcharge__c: true,
            ApplyEnhancedSafetyFee__c: true,
            Apply_EEC__c: true,
          },
          SBQQ__ProductOption__r: {
            attributes: {
              type: 'SBQQ__ProductOption__c',
              url: '/services/data/v58.0/sobjects/SBQQ__ProductOption__c/a6D8I0000008aJdUAI',
            },
            Id: 'a6D8I0000008aJdUAI',
            SBQQ__Number__c: 1,
          },
        },
        {
          attributes: {
            type: 'SBQQ__QuoteLine__c',
            url: '/services/data/v58.0/sobjects/SBQQ__QuoteLine__c/a6KVA000000NjSm2AK',
          },
          Id: 'a6KVA000000NjSm2AK',
          SBQQ__Quote__c: 'a6OVA0000006Izx2AE',
          SBQQ__Number__c: 5,
          Name: 'QL-8397061',
          Product_Name__c: 'Pick Hand per Unit',
          Sort_Order__c: '00000000500001',
          QuantityUnitOfMeasure__c: 'Each',
          SBQQ__Taxable__c: false,
          SBQQ__Quantity__c: 1,
          IS2PContractedPrice__c: false,
          SBQQ__SpecialPriceType__c: null,
          SBQQ__ListPrice__c: 5,
          Floor_Price__c: 15,
          SBQQ__UnitCost__c: null,
          SBQQ__NetPrice__c: 1517.3,
          SBQQ__CustomerPrice__c: 1517.3,
          Price_Override__c: 15,
          SBQQ__EffectiveStartDate__c: '2024-09-18',
          Total_Sales_Tax_Amount__c: 0,
          Apply_Houston_Franchise_Fee__c: true,
          Houston_Franchise_Fees_Percent__c: 0,
          Houston_Franchise_Fee_Per_Unit__c: 0,
          Houston_Franchise_Fees__c: 0,
          Apply_Fuel_Surcharge__c: true,
          Fuel_Surcharge_Percent__c: 14.9,
          Fuel_Surcharge_Amount__c: 2.24,
          Fuel_Surcharge_Per_Unit__c: 2.24,
          Product_Type__c: 'P n D',
          SBQQ__RequiredBy__c: 'a6KVA000000NjSf2AK',
          USS_Net__c: 15,
          SBQQ__ChargeType__c: 'One-Time',
          EEC_Charge__c: 1.5,
          ESF_Charge__c: 0.15,
          SBQQ__StartDate__c: '2024-09-18',
          SBQQ__EndDate__c: '2049-12-31',
          SBQQ__PricebookEntryId__c: '01u3m00000O2tVKAAZ',
          SBQQ__SubscriptionTerm__c: null,
          SBQQ__ProductSubscriptionType__c: 'One-time',
          SBQQ__ProrateMultiplier__c: 303.46027397260275,
          SBQQ__SubscriptionPricing__c: 'Fixed Price',
          SBQQ__SubscriptionType__c: 'One-time',
          SBQQ__DefaultSubscriptionTerm__c: 1,
          SBQQ__ProductCode__c: '123-3010',
          AVA_SFCPQ__Location_Code__c: null,
          USF_Address__c: 'a8x8I000000CoKpQAK',
          SBQQ__TaxCode__c: 'FR010000',
          Ship_From_Street__c: '31 East Belcher Rd',
          Ship_From_City__c: 'Foxboro',
          Ship_From_State__c: 'Massachusetts',
          Ship_From_Zipcode__c: '02035',
          AVA_SFCPQ__TaxAmount__c: 0,
          ESF_Percent__c: 1,
          EEC_Percent__c: 10,
          SBQQ__Product__c: '01t3m00000POh0MAAT',
          SBQQ__Product__r: {
            attributes: {
              type: 'Product2',
              url: '/services/data/v58.0/sobjects/Product2/01t3m00000POh0MAAT',
            },
            Id: '01t3m00000POh0MAAT',
            Name: 'Pick Hand per Unit',
            ProductCode: '123-3010',
            Description: 'Pickup Hand Cleaning - Per Unit Charge',
            Asset_Summary__c: 'Non-fees Sanitation',
            Apply_Fuel_Surcharge__c: true,
            ApplyEnhancedSafetyFee__c: true,
            Apply_EEC__c: true,
          },
          SBQQ__ProductOption__r: {
            attributes: {
              type: 'SBQQ__ProductOption__c',
              url: '/services/data/v58.0/sobjects/SBQQ__ProductOption__c/a6D8I0000008aN6UAI',
            },
            Id: 'a6D8I0000008aN6UAI',
            SBQQ__Number__c: 1,
          },
        },
        {
          attributes: {
            type: 'SBQQ__QuoteLine__c',
            url: '/services/data/v58.0/sobjects/SBQQ__QuoteLine__c/a6KVA000000NjSn2AK',
          },
          Id: 'a6KVA000000NjSn2AK',
          SBQQ__Quote__c: 'a6OVA0000006Izx2AE',
          SBQQ__Number__c: 7,
          Name: 'QL-8397062',
          Product_Name__c: 'Std Rest',
          Sort_Order__c: '00000000700010',
          QuantityUnitOfMeasure__c: 'Each',
          SBQQ__Taxable__c: true,
          SBQQ__Quantity__c: 2,
          IS2PContractedPrice__c: false,
          SBQQ__SpecialPriceType__c: null,
          SBQQ__ListPrice__c: 20,
          Floor_Price__c: 40,
          SBQQ__UnitCost__c: null,
          SBQQ__NetPrice__c: 6069.21,
          SBQQ__CustomerPrice__c: 6069.21,
          Price_Override__c: 40,
          SBQQ__EffectiveStartDate__c: '2024-09-18',
          Total_Sales_Tax_Amount__c: 6.25,
          Apply_Houston_Franchise_Fee__c: true,
          Houston_Franchise_Fees_Percent__c: 0,
          Houston_Franchise_Fee_Per_Unit__c: 0,
          Houston_Franchise_Fees__c: 0,
          Apply_Fuel_Surcharge__c: true,
          Fuel_Surcharge_Percent__c: 14.9,
          Fuel_Surcharge_Amount__c: 11.92,
          Fuel_Surcharge_Per_Unit__c: 5.96,
          Product_Type__c: 'Asset',
          SBQQ__RequiredBy__c: 'a6KVA000000NjSg2AK',
          USS_Net__c: 80,
          SBQQ__ChargeType__c: 'Recurring',
          EEC_Charge__c: 8,
          ESF_Charge__c: 0,
          SBQQ__StartDate__c: '2024-09-18',
          SBQQ__EndDate__c: '2049-12-31',
          SBQQ__PricebookEntryId__c: '01u3m00000O2tTvAAJ',
          SBQQ__SubscriptionTerm__c: null,
          SBQQ__ProductSubscriptionType__c: 'Renewable',
          SBQQ__ProrateMultiplier__c: 303.46027397260275,
          SBQQ__SubscriptionPricing__c: 'Fixed Price',
          SBQQ__SubscriptionType__c: 'Renewable',
          SBQQ__DefaultSubscriptionTerm__c: 1,
          SBQQ__ProductCode__c: '111-1001',
          AVA_SFCPQ__Location_Code__c: null,
          USF_Address__c: 'a8x8I000000CoKpQAK',
          SBQQ__TaxCode__c: 'SANIRENT',
          Ship_From_Street__c: '31 East Belcher Rd',
          Ship_From_City__c: 'Foxboro',
          Ship_From_State__c: 'Massachusetts',
          Ship_From_Zipcode__c: '02035',
          AVA_SFCPQ__TaxAmount__c: 5,
          ESF_Percent__c: 0,
          EEC_Percent__c: 10,
          SBQQ__Product__c: '01t3m00000NTiw6AAD',
          SBQQ__Product__r: {
            attributes: {
              type: 'Product2',
              url: '/services/data/v58.0/sobjects/Product2/01t3m00000NTiw6AAD',
            },
            Id: '01t3m00000NTiw6AAD',
            Name: 'Std Rest',
            ProductCode: '111-1001',
            Description: 'Standard Restroom',
            Asset_Summary__c: 'Standard Restroom',
            Apply_Fuel_Surcharge__c: true,
            ApplyEnhancedSafetyFee__c: false,
            Apply_EEC__c: true,
          },
          SBQQ__ProductOption__r: {
            attributes: {
              type: 'SBQQ__ProductOption__c',
              url: '/services/data/v58.0/sobjects/SBQQ__ProductOption__c/a6D8I0000008aKcUAI',
            },
            Id: 'a6D8I0000008aKcUAI',
            SBQQ__Number__c: 10,
          },
        },
        {
          attributes: {
            type: 'SBQQ__QuoteLine__c',
            url: '/services/data/v58.0/sobjects/SBQQ__QuoteLine__c/a6KVA000000NjSo2AK',
          },
          Id: 'a6KVA000000NjSo2AK',
          SBQQ__Quote__c: 'a6OVA0000006Izx2AE',
          SBQQ__Number__c: 8,
          Name: 'QL-8397063',
          Product_Name__c: '1 Svc 2 Days Wk',
          Sort_Order__c: '00000000800020',
          QuantityUnitOfMeasure__c: 'Each',
          SBQQ__Taxable__c: false,
          SBQQ__Quantity__c: 2,
          IS2PContractedPrice__c: false,
          SBQQ__SpecialPriceType__c: null,
          SBQQ__ListPrice__c: 160,
          Floor_Price__c: 298,
          SBQQ__UnitCost__c: null,
          SBQQ__NetPrice__c: 48553.64,
          SBQQ__CustomerPrice__c: 48553.64,
          Price_Override__c: 351,
          SBQQ__EffectiveStartDate__c: '2024-09-18',
          Total_Sales_Tax_Amount__c: 0,
          Apply_Houston_Franchise_Fee__c: true,
          Houston_Franchise_Fees_Percent__c: 0,
          Houston_Franchise_Fee_Per_Unit__c: 0,
          Houston_Franchise_Fees__c: 0,
          Apply_Fuel_Surcharge__c: true,
          Fuel_Surcharge_Percent__c: 14.9,
          Fuel_Surcharge_Amount__c: 104.6,
          Fuel_Surcharge_Per_Unit__c: 52.3,
          Product_Type__c: 'Service',
          SBQQ__RequiredBy__c: 'a6KVA000000NjSg2AK',
          USS_Net__c: 702,
          SBQQ__ChargeType__c: 'Recurring',
          EEC_Charge__c: 70.2,
          ESF_Charge__c: 7.02,
          SBQQ__StartDate__c: '2024-09-18',
          SBQQ__EndDate__c: '2049-12-31',
          SBQQ__PricebookEntryId__c: '01u3m00000O2tYTAAZ',
          SBQQ__SubscriptionTerm__c: null,
          SBQQ__ProductSubscriptionType__c: 'Renewable',
          SBQQ__ProrateMultiplier__c: 303.46027397260275,
          SBQQ__SubscriptionPricing__c: 'Fixed Price',
          SBQQ__SubscriptionType__c: 'Renewable',
          SBQQ__DefaultSubscriptionTerm__c: 1,
          SBQQ__ProductCode__c: '112-2002',
          AVA_SFCPQ__Location_Code__c: null,
          USF_Address__c: 'a8x8I000000CoKpQAK',
          SBQQ__TaxCode__c: 'TOILETSERV',
          Ship_From_Street__c: '31 East Belcher Rd',
          Ship_From_City__c: 'Foxboro',
          Ship_From_State__c: 'Massachusetts',
          Ship_From_Zipcode__c: '02035',
          AVA_SFCPQ__TaxAmount__c: 0,
          ESF_Percent__c: 1,
          EEC_Percent__c: 10,
          SBQQ__Product__c: '01t3m00000POgudAAD',
          SBQQ__Product__r: {
            attributes: {
              type: 'Product2',
              url: '/services/data/v58.0/sobjects/Product2/01t3m00000POgudAAD',
            },
            Id: '01t3m00000POgudAAD',
            Name: '1 Svc 2 Days Wk',
            ProductCode: '112-2002',
            Description: '1 Service 2 Days per Week',
            Asset_Summary__c: 'Group A Sanitation',
            Apply_Fuel_Surcharge__c: true,
            ApplyEnhancedSafetyFee__c: true,
            Apply_EEC__c: true,
          },
          SBQQ__ProductOption__r: {
            attributes: {
              type: 'SBQQ__ProductOption__c',
              url: '/services/data/v58.0/sobjects/SBQQ__ProductOption__c/a6D8I0000008aNLUAY',
            },
            Id: 'a6D8I0000008aNLUAY',
            SBQQ__Number__c: 20,
          },
        },
        {
          attributes: {
            type: 'SBQQ__QuoteLine__c',
            url: '/services/data/v58.0/sobjects/SBQQ__QuoteLine__c/a6KVA000000NjSp2AK',
          },
          Id: 'a6KVA000000NjSp2AK',
          SBQQ__Quote__c: 'a6OVA0000006Izx2AE',
          SBQQ__Number__c: 9,
          Name: 'QL-8397064',
          Product_Name__c: 'Del Rest per Unit',
          Sort_Order__c: '00000000900010',
          QuantityUnitOfMeasure__c: 'Each',
          SBQQ__Taxable__c: false,
          SBQQ__Quantity__c: 2,
          IS2PContractedPrice__c: false,
          SBQQ__SpecialPriceType__c: null,
          SBQQ__ListPrice__c: 5,
          Floor_Price__c: 15,
          SBQQ__UnitCost__c: null,
          SBQQ__NetPrice__c: 1517.3,
          SBQQ__CustomerPrice__c: 1517.3,
          Price_Override__c: 15,
          SBQQ__EffectiveStartDate__c: '2024-09-18',
          Total_Sales_Tax_Amount__c: 0,
          Apply_Houston_Franchise_Fee__c: true,
          Houston_Franchise_Fees_Percent__c: 0,
          Houston_Franchise_Fee_Per_Unit__c: 0,
          Houston_Franchise_Fees__c: 0,
          Apply_Fuel_Surcharge__c: true,
          Fuel_Surcharge_Percent__c: 14.9,
          Fuel_Surcharge_Amount__c: 4.48,
          Fuel_Surcharge_Per_Unit__c: 2.24,
          Product_Type__c: 'P n D',
          SBQQ__RequiredBy__c: 'a6KVA000000NjSg2AK',
          USS_Net__c: 30,
          SBQQ__ChargeType__c: 'One-Time',
          EEC_Charge__c: 3,
          ESF_Charge__c: 0.3,
          SBQQ__StartDate__c: '2024-09-18',
          SBQQ__EndDate__c: '2049-12-31',
          SBQQ__PricebookEntryId__c: '01u3m00000O2tVpAAJ',
          SBQQ__SubscriptionTerm__c: null,
          SBQQ__ProductSubscriptionType__c: 'One-time',
          SBQQ__ProrateMultiplier__c: 303.46027397260275,
          SBQQ__SubscriptionPricing__c: 'Fixed Price',
          SBQQ__SubscriptionType__c: 'One-time',
          SBQQ__DefaultSubscriptionTerm__c: 1,
          SBQQ__ProductCode__c: '113-3009',
          AVA_SFCPQ__Location_Code__c: null,
          USF_Address__c: 'a8x8I000000CoKpQAK',
          SBQQ__TaxCode__c: 'FR010000',
          Ship_From_Street__c: '31 East Belcher Rd',
          Ship_From_City__c: 'Foxboro',
          Ship_From_State__c: 'Massachusetts',
          Ship_From_Zipcode__c: '02035',
          AVA_SFCPQ__TaxAmount__c: 0,
          ESF_Percent__c: 1,
          EEC_Percent__c: 10,
          SBQQ__Product__c: '01t3m00000POgxIAAT',
          SBQQ__Product__r: {
            attributes: {
              type: 'Product2',
              url: '/services/data/v58.0/sobjects/Product2/01t3m00000POgxIAAT',
            },
            Id: '01t3m00000POgxIAAT',
            Name: 'Del Rest per Unit',
            ProductCode: '113-3009',
            Description: 'Delivery Restroom - Per Unit Charge',
            Asset_Summary__c: 'Non-fees Sanitation',
            Apply_Fuel_Surcharge__c: true,
            ApplyEnhancedSafetyFee__c: true,
            Apply_EEC__c: true,
          },
          SBQQ__ProductOption__r: {
            attributes: {
              type: 'SBQQ__ProductOption__c',
              url: '/services/data/v58.0/sobjects/SBQQ__ProductOption__c/a6D8I0000008aMRUAY',
            },
            Id: 'a6D8I0000008aMRUAY',
            SBQQ__Number__c: 10,
          },
        },
        {
          attributes: {
            type: 'SBQQ__QuoteLine__c',
            url: '/services/data/v58.0/sobjects/SBQQ__QuoteLine__c/a6KVA000000NjSq2AK',
          },
          Id: 'a6KVA000000NjSq2AK',
          SBQQ__Quote__c: 'a6OVA0000006Izx2AE',
          SBQQ__Number__c: 10,
          Name: 'QL-8397065',
          Product_Name__c: 'Pick Rest per Unit',
          Sort_Order__c: '00000001000010',
          QuantityUnitOfMeasure__c: 'Each',
          SBQQ__Taxable__c: false,
          SBQQ__Quantity__c: 2,
          IS2PContractedPrice__c: false,
          SBQQ__SpecialPriceType__c: null,
          SBQQ__ListPrice__c: 5,
          Floor_Price__c: 15,
          SBQQ__UnitCost__c: null,
          SBQQ__NetPrice__c: 1517.3,
          SBQQ__CustomerPrice__c: 1517.3,
          Price_Override__c: 15,
          SBQQ__EffectiveStartDate__c: '2024-09-18',
          Total_Sales_Tax_Amount__c: 0,
          Apply_Houston_Franchise_Fee__c: true,
          Houston_Franchise_Fees_Percent__c: 0,
          Houston_Franchise_Fee_Per_Unit__c: 0,
          Houston_Franchise_Fees__c: 0,
          Apply_Fuel_Surcharge__c: true,
          Fuel_Surcharge_Percent__c: 14.9,
          Fuel_Surcharge_Amount__c: 4.48,
          Fuel_Surcharge_Per_Unit__c: 2.24,
          Product_Type__c: 'P n D',
          SBQQ__RequiredBy__c: 'a6KVA000000NjSg2AK',
          USS_Net__c: 30,
          SBQQ__ChargeType__c: 'One-Time',
          EEC_Charge__c: 3,
          ESF_Charge__c: 0.3,
          SBQQ__StartDate__c: '2024-09-18',
          SBQQ__EndDate__c: '2049-12-31',
          SBQQ__PricebookEntryId__c: '01u3m00000O2tWPAAZ',
          SBQQ__SubscriptionTerm__c: null,
          SBQQ__ProductSubscriptionType__c: 'One-time',
          SBQQ__ProrateMultiplier__c: 303.46027397260275,
          SBQQ__SubscriptionPricing__c: 'Fixed Price',
          SBQQ__SubscriptionType__c: 'One-time',
          SBQQ__DefaultSubscriptionTerm__c: 1,
          SBQQ__ProductCode__c: '113-3010',
          AVA_SFCPQ__Location_Code__c: null,
          USF_Address__c: 'a8x8I000000CoKpQAK',
          SBQQ__TaxCode__c: 'FR010000',
          Ship_From_Street__c: '31 East Belcher Rd',
          Ship_From_City__c: 'Foxboro',
          Ship_From_State__c: 'Massachusetts',
          Ship_From_Zipcode__c: '02035',
          AVA_SFCPQ__TaxAmount__c: 0,
          ESF_Percent__c: 1,
          EEC_Percent__c: 10,
          SBQQ__Product__c: '01t3m00000POgxNAAT',
          SBQQ__Product__r: {
            attributes: {
              type: 'Product2',
              url: '/services/data/v58.0/sobjects/Product2/01t3m00000POgxNAAT',
            },
            Id: '01t3m00000POgxNAAT',
            Name: 'Pick Rest per Unit',
            ProductCode: '113-3010',
            Description: 'Pickup Restroom - Per Unit Charge',
            Asset_Summary__c: 'Non-fees Sanitation',
            Apply_Fuel_Surcharge__c: true,
            ApplyEnhancedSafetyFee__c: true,
            Apply_EEC__c: true,
          },
          SBQQ__ProductOption__r: {
            attributes: {
              type: 'SBQQ__ProductOption__c',
              url: '/services/data/v58.0/sobjects/SBQQ__ProductOption__c/a6D8I0000008aV2UAI',
            },
            Id: 'a6D8I0000008aV2UAI',
            SBQQ__Number__c: 10,
          },
        },
      ],
    },
    NF_Quoted_Jobsites__r: {
      totalSize: 3,
      done: true,
      records: [
        {
          attributes: {
            type: 'NF_Quoted_Jobsite__c',
            url: '/services/data/v58.0/sobjects/NF_Quoted_Jobsite__c/aFJVA0000001jj34AA',
          },
          Id: 'aFJVA0000001jj34AA',
          Name: 'QJ-268764',
          NF_Quote__c: 'a6OVA0000006Izx2AE',
          NF_End_Date__c: '2049-12-31',
          NF_Start_Date__c: '2024-09-18',
          NF_Quote_Line__c: 'a6KVA000000NjSf2AK',
          NF_Quote_Line__r: {
            attributes: {
              type: 'SBQQ__QuoteLine__c',
              url: '/services/data/v58.0/sobjects/SBQQ__QuoteLine__c/a6KVA000000NjSf2AK',
            },
            SBQQ__Product__r: {
              attributes: {
                type: 'Product2',
                url: '/services/data/v58.0/sobjects/Product2/01t3m00000PPH5RAAX',
              },
              Id: '01t3m00000PPH5RAAX',
              Name: 'Hand Cleaning Bundle',
              ProductCode: '120-0000',
              Description: 'Hand Cleaning Bundle Configuration',
              Asset_Summary__c: null,
            },
          },
          NF_Aggregated_Product_Name__c: '2 Station Hand Wash Sink  1 Service 2 Days per Week',
          NF_Quantity_Quoted__c: 1,
          NF_USF_Address__r: {
            attributes: {
              type: 'USF_Address__c',
              url: '/services/data/v58.0/sobjects/USF_Address__c/a8xVA000000iSQPYA2',
            },
            Id: 'a8xVA000000iSQPYA2',
            USF_Account__c: '0018I00000jIg0sQAC',
            Name: '136 Pleasant Street - Brookline - MA',
            NF_Parent_USF_Address__c: 'a8x8I000000CoKpQAK',
            USF_Street__c: '136 Pleasant Street',
            USF_City__c: 'Brookline',
            USF_State__c: 'MA',
            USF_Zip_Code__c: '02446',
            USF_Country__c: 'US',
            Address_Latitude_Longitude__Latitude__s: 42.34714,
            Address_Latitude_Longitude__Longitude__s: -71.11867,
            Is_Primary__c: false,
            USF_Ship_To_Address__c: true,
            USF_Bill_To_Address__c: false,
            NF_Is_Parent__c: false,
            Address_Validated__c: true,
            GeoCode_Accuracy__c: 'Address',
            Site_Name__c: '136 Pleasant Street',
            NF_Site_Hours_Start_Time__c: '09:00:00.125Z',
            NF_Site_Hours_End_Time__c: '21:00:00.125Z',
            NF_Arrival_Start_Time__c: null,
            NF_Arrival_End_Time__c: null,
            NF_Gate_Code__c: null,
            NF_Access_instructions__c: null,
            NF_Key_Instructions__c: null,
            NF_Other_Instructions__c: null,
            NF_Background_Check__c: false,
            NF_Clearance_Required__c: false,
            Additional_Information__c: null,
            NF_Ship_To_Contact__r: {
              attributes: {
                type: 'Contact',
                url: '/services/data/v58.0/sobjects/Contact/0038I00000fn3IZQAY',
              },
              Id: '0038I00000fn3IZQAY',
              FirstName: 'Sanjiv b',
              LastName: 'Shinde',
              Phone: '+918380096983',
              Email: 'sanjivbshinde@gmail.com',
            },
            NF_Placement__c: 'ok',
          },
        },
        {
          attributes: {
            type: 'NF_Quoted_Jobsite__c',
            url: '/services/data/v58.0/sobjects/NF_Quoted_Jobsite__c/aFJVA0000001jj44AA',
          },
          Id: 'aFJVA0000001jj44AA',
          Name: 'QJ-268765',
          NF_Quote__c: 'a6OVA0000006Izx2AE',
          NF_End_Date__c: '2049-12-31',
          NF_Start_Date__c: '2024-09-18',
          NF_Quote_Line__c: 'a6KVA000000NjSg2AK',
          NF_Quote_Line__r: {
            attributes: {
              type: 'SBQQ__QuoteLine__c',
              url: '/services/data/v58.0/sobjects/SBQQ__QuoteLine__c/a6KVA000000NjSg2AK',
            },
            SBQQ__Product__r: {
              attributes: {
                type: 'Product2',
                url: '/services/data/v58.0/sobjects/Product2/01t3m00000PPH5MAAX',
              },
              Id: '01t3m00000PPH5MAAX',
              Name: 'Restroom Bundle',
              ProductCode: '110-0000',
              Description: 'Restroom Bundle Configuration',
              Asset_Summary__c: null,
            },
          },
          NF_Aggregated_Product_Name__c: 'Standard Restroom  1 Service 2 Days per Week',
          NF_Quantity_Quoted__c: 1,
          NF_USF_Address__r: {
            attributes: {
              type: 'USF_Address__c',
              url: '/services/data/v58.0/sobjects/USF_Address__c/a8xVA000000iSQPYA2',
            },
            Id: 'a8xVA000000iSQPYA2',
            USF_Account__c: '0018I00000jIg0sQAC',
            Name: '136 Pleasant Street - Brookline - MA',
            NF_Parent_USF_Address__c: 'a8x8I000000CoKpQAK',
            USF_Street__c: '136 Pleasant Street',
            USF_City__c: 'Brookline',
            USF_State__c: 'MA',
            USF_Zip_Code__c: '02446',
            USF_Country__c: 'US',
            Address_Latitude_Longitude__Latitude__s: 42.34714,
            Address_Latitude_Longitude__Longitude__s: -71.11867,
            Is_Primary__c: false,
            USF_Ship_To_Address__c: true,
            USF_Bill_To_Address__c: false,
            NF_Is_Parent__c: false,
            Address_Validated__c: true,
            GeoCode_Accuracy__c: 'Address',
            Site_Name__c: '136 Pleasant Street',
            NF_Site_Hours_Start_Time__c: '09:00:00.125Z',
            NF_Site_Hours_End_Time__c: '21:00:00.125Z',
            NF_Arrival_Start_Time__c: null,
            NF_Arrival_End_Time__c: null,
            NF_Gate_Code__c: null,
            NF_Access_instructions__c: null,
            NF_Key_Instructions__c: null,
            NF_Other_Instructions__c: null,
            NF_Background_Check__c: false,
            NF_Clearance_Required__c: false,
            Additional_Information__c: null,
            NF_Ship_To_Contact__r: {
              attributes: {
                type: 'Contact',
                url: '/services/data/v58.0/sobjects/Contact/0038I00000fn3IZQAY',
              },
              Id: '0038I00000fn3IZQAY',
              FirstName: 'Sanjiv b',
              LastName: 'Shinde',
              Phone: '+918380096983',
              Email: 'sanjivbshinde@gmail.com',
            },
            NF_Placement__c: 'ok',
          },
        },
        {
          attributes: {
            type: 'NF_Quoted_Jobsite__c',
            url: '/services/data/v58.0/sobjects/NF_Quoted_Jobsite__c/aFJVA0000001jj54AA',
          },
          Id: 'aFJVA0000001jj54AA',
          Name: 'QJ-268766',
          NF_Quote__c: 'a6OVA0000006Izx2AE',
          NF_End_Date__c: '2049-12-31',
          NF_Start_Date__c: '2024-09-18',
          NF_Quote_Line__c: 'a6KVA000000NjSg2AK',
          NF_Quote_Line__r: {
            attributes: {
              type: 'SBQQ__QuoteLine__c',
              url: '/services/data/v58.0/sobjects/SBQQ__QuoteLine__c/a6KVA000000NjSg2AK',
            },
            SBQQ__Product__r: {
              attributes: {
                type: 'Product2',
                url: '/services/data/v58.0/sobjects/Product2/01t3m00000PPH5MAAX',
              },
              Id: '01t3m00000PPH5MAAX',
              Name: 'Restroom Bundle',
              ProductCode: '110-0000',
              Description: 'Restroom Bundle Configuration',
              Asset_Summary__c: null,
            },
          },
          NF_Aggregated_Product_Name__c: 'Standard Restroom  1 Service 2 Days per Week',
          NF_Quantity_Quoted__c: 1,
          NF_USF_Address__r: {
            attributes: {
              type: 'USF_Address__c',
              url: '/services/data/v58.0/sobjects/USF_Address__c/a8xVA000000iSS1YAM',
            },
            Id: 'a8xVA000000iSS1YAM',
            USF_Account__c: '0018I00000jIg0sQAC',
            Name: '136 Pleasant Street - Brookline - MA',
            NF_Parent_USF_Address__c: 'a8x8I000000CoKpQAK',
            USF_Street__c: '136 Pleasant Street',
            USF_City__c: 'Brookline',
            USF_State__c: 'MA',
            USF_Zip_Code__c: '02446',
            USF_Country__c: 'US',
            Address_Latitude_Longitude__Latitude__s: 42.34714,
            Address_Latitude_Longitude__Longitude__s: -71.11867,
            Is_Primary__c: false,
            USF_Ship_To_Address__c: true,
            USF_Bill_To_Address__c: false,
            NF_Is_Parent__c: false,
            Address_Validated__c: true,
            GeoCode_Accuracy__c: 'Address',
            Site_Name__c: 'Boston high street',
            NF_Site_Hours_Start_Time__c: '09:00:00.125Z',
            NF_Site_Hours_End_Time__c: '21:00:00.125Z',
            NF_Arrival_Start_Time__c: null,
            NF_Arrival_End_Time__c: null,
            NF_Gate_Code__c: null,
            NF_Access_instructions__c: null,
            NF_Key_Instructions__c: null,
            NF_Other_Instructions__c: null,
            NF_Background_Check__c: false,
            NF_Clearance_Required__c: false,
            Additional_Information__c: null,
            NF_Ship_To_Contact__r: {
              attributes: {
                type: 'Contact',
                url: '/services/data/v58.0/sobjects/Contact/0038I00000fn3IZQAY',
              },
              Id: '0038I00000fn3IZQAY',
              FirstName: 'Sanjiv b',
              LastName: 'Shinde',
              Phone: '+918380096983',
              Email: 'sanjivbshinde@gmail.com',
            },
            NF_Placement__c: 'Keep quite',
          },
        },
      ],
    },
    SBQQ__R00N70000001lX7YEAU__r: {
      totalSize: 1,
      done: true,
      records: [
        {
          attributes: {
            type: 'SBQQ__QuoteDocument__c',
            url: '/services/data/v58.0/sobjects/SBQQ__QuoteDocument__c/a6FVA000000CvCD2A0',
          },
          Id: 'a6FVA000000CvCD2A0',
          Name: 'SANJIV-Account Quote 08.22.2024',
          SBQQ__DocumentId__c: '015VA000000N4xNYAS',
          SBQQ__Version__c: 1,
        },
      ],
    },
  };

  let getQuoteDetailsSuccessResponse = {
    status: 1000,
    message: 'Success',
    success :true,
    data: {
      quoteModel: {
        quoteId: 'a6OVA0000006Izx2AE',
        quoteNumber: 'Q-521314',
        quoteName: 'MyUSS Quote 2024-08-22T11:51:55.563Z',
        account: {
          id: '0018I00000jIg0sQAC',
          name: 'SANJIV-Account',
          accountNumber: 'ACT-01640742',
          requirements: {
            autoPay: false,
          },
          defaultBillingDetails: {
            billingAddress: {},
          },
          accountOwner: {
            id: '0058I000002oBmXQAU',
            firstName: 'MyUSS',
            lastName: 'System User',
            title: null,
            phone: null,
            email: 'myussadmin@unitedsiteservices.com',
          },
        },
        startDate: '2024-09-18',
        endDate: '2049-12-31',
        primaryContact: {
          id: '0038I00000fn3IZQAY',
          firstName: 'Sanjiv b',
          lastName: 'Shinde',
          phone: '+918380096983',
          email: 'sanjivbshinde@gmail.com',
          fullName: 'Sanjiv b Shinde',
        },
        primarySiteContact: {
          id: '0038I00000fn3IZQAY',
          firstName: 'Sanjiv b',
          lastName: 'Shinde',
          phone: '+918380096983',
          email: 'sanjivbshinde@gmail.com',
          fullName: 'Sanjiv b Shinde',
        },
        secondaryContactData: {},
        shippingAddress: {
          id: 'a8x8I000000CoKpQAK',
          accountId: '0018I00000jIg0sQAC',
          name: '136 Pleasant Street - Brookline - MA',
          street: '136 Pleasant Street',
          city: 'Brookline',
          state: 'MA',
          zipcode: '02446',
          country: 'US',
          latitude: 42.34714,
          longitude: -71.11867,
          addressValidated: true,
          placementNotes: '090',
          startTime: '09:00:00.125Z',
          endTime: '21:00:00.125Z',
          instructions: '090',
          information: 'PL Note12',
          geocodeAccuracy: 'Address',
          siteName: '136 Pleasant Street - Brookline - MA',
          gateCode: 'Gate 300',
          siteContact: null,
          secondarySiteContact: null,
          shipToContact: null,
          isShippingAddress: true,
          isBillingAddress: false,
          isParentAddress: true,
          idRequired: true,
          clearanceRequired: true,
        },
        isAutoPay: true,
        billToAddress: {},
        billingComplete: false,
        orderedinSalesforce: true,
        paymentMethodId: null,
        paymentMode: 'creditDebit',
        siteComplete: true,
        purchaseOrder: {
          accountId: '',
        },
        status: 'Approved',
        currentStatus: 4,
        ordered: false,
        billCycleDay: null,
        chargeType: 'Recurring',
        eECPercent: 10,
        eSFPercent: 1,
        fuelSurchargePercent: 14.9,
        lastBillingDate: null,
        legalEntity: 'United Site Services Northeast, Inc.',
        jobSites: [
          {
            id: 'aFJVA0000001jj34AA',
            name: 'QJ-268764',
            placedProductName: '2 Station Hand Wash Sink  1 Service 2 Days per Week',
            address: {
              id: 'a8xVA000000iSQPYA2',
              accountId: '0018I00000jIg0sQAC',
              name: '136 Pleasant Street - Brookline - MA',
              street: '136 Pleasant Street',
              city: 'Brookline',
              state: 'MA',
              zipcode: '02446',
              country: 'US',
              latitude: 42.34714,
              longitude: -71.11867,
              addressValidated: true,
              placementNotes: 'ok',
              startTime: '09:00:00.125Z',
              endTime: '21:00:00.125Z',
              instructions: 'ok',
              information: null,
              geocodeAccuracy: 'Address',
              siteName: '136 Pleasant Street',
              gateCode: null,
              siteContact: null,
              secondarySiteContact: null,
              shipToContact: {
                id: '0038I00000fn3IZQAY',
                firstName: 'Sanjiv b',
                lastName: 'Shinde',
                phone: '+918380096983',
                email: 'sanjivbshinde@gmail.com',
                fullName: 'Sanjiv b Shinde',
              },
              isShippingAddress: true,
              isBillingAddress: false,
              isParentAddress: false,
              idRequired: false,
              clearanceRequired: false,
            },
            contact: {
              id: '0038I00000fn3IZQAY',
              firstName: 'Sanjiv b',
              lastName: 'Shinde',
              phone: '+918380096983',
              email: 'sanjivbshinde@gmail.com',
              fullName: 'Sanjiv b Shinde',
            },
            quantityQuoted: 1,
            quoteLineId: 'a6KVA000000NjSf2AK',
            productDetails: {
              bundleId: '01t3m00000PPH5RAAX',
              assetId: '01t3m00000NTiuFAAT',
              serviceId: '01t3m00000POgyQAAT',
              bundleName: 'Hand Cleaning Bundle Configuration',
              assetName: '2 Station Hand Wash Sink',
              serviceName: '1 Service 2 Days per Week',
              ancillaryServiceList: [],
              quantity: 1,
            },
          },
          {
            id: 'aFJVA0000001jj44AA',
            name: 'QJ-268765',
            placedProductName: 'Standard Restroom  1 Service 2 Days per Week',
            address: {
              id: 'a8xVA000000iSQPYA2',
              accountId: '0018I00000jIg0sQAC',
              name: '136 Pleasant Street - Brookline - MA',
              street: '136 Pleasant Street',
              city: 'Brookline',
              state: 'MA',
              zipcode: '02446',
              country: 'US',
              latitude: 42.34714,
              longitude: -71.11867,
              addressValidated: true,
              placementNotes: 'ok',
              startTime: '09:00:00.125Z',
              endTime: '21:00:00.125Z',
              instructions: 'ok',
              information: null,
              geocodeAccuracy: 'Address',
              siteName: '136 Pleasant Street',
              gateCode: null,
              siteContact: null,
              secondarySiteContact: null,
              shipToContact: {
                id: '0038I00000fn3IZQAY',
                firstName: 'Sanjiv b',
                lastName: 'Shinde',
                phone: '+918380096983',
                email: 'sanjivbshinde@gmail.com',
                fullName: 'Sanjiv b Shinde',
              },
              isShippingAddress: true,
              isBillingAddress: false,
              isParentAddress: false,
              idRequired: false,
              clearanceRequired: false,
            },
            contact: {
              id: '0038I00000fn3IZQAY',
              firstName: 'Sanjiv b',
              lastName: 'Shinde',
              phone: '+918380096983',
              email: 'sanjivbshinde@gmail.com',
              fullName: 'Sanjiv b Shinde',
            },
            quantityQuoted: 1,
            quoteLineId: 'a6KVA000000NjSg2AK',
            productDetails: {
              bundleId: '01t3m00000PPH5MAAX',
              assetId: '01t3m00000NTiw6AAD',
              serviceId: '01t3m00000POgudAAD',
              bundleName: 'Restroom Bundle Configuration',
              assetName: 'Standard Restroom',
              serviceName: '1 Service 2 Days per Week',
              ancillaryServiceList: [],
              quantity: 2,
            },
          },
          {
            id: 'aFJVA0000001jj54AA',
            name: 'QJ-268766',
            placedProductName: 'Standard Restroom  1 Service 2 Days per Week',
            address: {
              id: 'a8xVA000000iSS1YAM',
              accountId: '0018I00000jIg0sQAC',
              name: '136 Pleasant Street - Brookline - MA',
              street: '136 Pleasant Street',
              city: 'Brookline',
              state: 'MA',
              zipcode: '02446',
              country: 'US',
              latitude: 42.34714,
              longitude: -71.11867,
              addressValidated: true,
              placementNotes: 'Keep quite',
              startTime: '09:00:00.125Z',
              endTime: '21:00:00.125Z',
              instructions: 'Keep quite',
              information: null,
              geocodeAccuracy: 'Address',
              siteName: 'Boston high street',
              gateCode: null,
              siteContact: null,
              secondarySiteContact: null,
              shipToContact: {
                id: '0038I00000fn3IZQAY',
                firstName: 'Sanjiv b',
                lastName: 'Shinde',
                phone: '+918380096983',
                email: 'sanjivbshinde@gmail.com',
                fullName: 'Sanjiv b Shinde',
              },
              isShippingAddress: true,
              isBillingAddress: false,
              isParentAddress: false,
              idRequired: false,
              clearanceRequired: false,
            },
            contact: {
              id: '0038I00000fn3IZQAY',
              firstName: 'Sanjiv b',
              lastName: 'Shinde',
              phone: '+918380096983',
              email: 'sanjivbshinde@gmail.com',
              fullName: 'Sanjiv b Shinde',
            },
            quantityQuoted: 1,
            quoteLineId: 'a6KVA000000NjSg2AK',
            productDetails: {
              bundleId: '01t3m00000PPH5MAAX',
              assetId: '01t3m00000NTiw6AAD',
              serviceId: '01t3m00000POgudAAD',
              bundleName: 'Restroom Bundle Configuration',
              assetName: 'Standard Restroom',
              serviceName: '1 Service 2 Days per Week',
              ancillaryServiceList: [],
              quantity: 2,
            },
          },
        ],
        quoteDocuments: [
          {
            documentId: '015VA000000N4xNYAS',
            documentName: 'SANJIV-Account Quote 08.22.2024',
            version: 1,
          },
        ],
        enableServerSidePricingCalculation: false,
        avaTaxCompanyCode: 'USNE',
        aVASFCPQIsSellerImporterOfRecord: false,
        avaSalesTaxAmount: 7.5,
        avaSalesTaxMessage: 'Tax Amount is Outdated',
        duration: '1-3 Months',
        quoteReferenceNumber: '521314',
        quoteDate: '2024-08-22',
        expirationDate: '09-21-24',
        quoteExpiryDate: '2024-09-21',
        ussContact: {
          firstName: 'Customer Care',
          lastName: '',
          title: '',
          phone: '1-888-320-1861',
          email: 'myussadmin@unitedsiteservices.com',
        },
        oneTimeSubtotal: 226.66,
        oneTimeTax: 0,
        oneTimeTotal: 226.66,
        recurringSubtotal: 1499.53,
        recurringTax: 9.37,
        recurringTotal: 1508.9,
        quoteLines: [
          {
            quoteLineId: 'a6KVA000000NjSf2AK',
            quoteId: 'a6OVA0000006Izx2AE',
            lineNumber: 1,
            name: 'QL-8397054',
            requiredBy: null,
            product: {
              id: '01t3m00000PPH5RAAX',
              productCode: '120-0000',
              name: 'Hand Cleaning Bundle',
              description: 'Hand Cleaning Bundle Configuration',
              assetSummary: null,
              applyFuelSurcharge: false,
              applyEnhancedSafetyFee: false,
              applyEEC: false,
            },
            quantity: 1,
            listPrice: 0,
            floorPrice: 0,
            unitCost: null,
            netPrice: 0,
            customerPrice: 0,
            salesTaxAmount: null,
            productType: 'Bundle',
            ussNetAmount: 0,
            chargeType: 'Recurring',
            startDate: '2024-09-18',
            endDate: '2049-12-31',
            priceBookId: '01u3m00000O2tSEAAZ',
            productSubscriptionType: 'Renewable',
            subscriptionType: 'Renewable',
            productCode: '120-0000',
            aVASFCPQLocationCode: null,
            taxable: true,
            taxCode: null,
            tax: 0,
            quantityUnitOfMeasure: null,
            sortOrder: '00000000100000',
            effectiveStartDate: '2024-09-18',
            applyHoustonFranchiseFee: false,
            houstonFranchiseFeePerUnit: 0,
            houstonFranchiseFeesPercent: 0,
            houstonFranchiseAmount: 0,
            applyFuelSurcharge: false,
            fuelSurchargePercent: 0,
            fuelSurchargeAmount: 0,
            fuelSurchargePerUnit: 0,
            EECPercent: 0,
            EECAmount: 0,
            ESFPercent: 0,
            ESFAmount: 0,
          },
          {
            quoteLineId: 'a6KVA000000NjSg2AK',
            quoteId: 'a6OVA0000006Izx2AE',
            lineNumber: 6,
            name: 'QL-8397055',
            requiredBy: null,
            product: {
              id: '01t3m00000PPH5MAAX',
              productCode: '110-0000',
              name: 'Restroom Bundle',
              description: 'Restroom Bundle Configuration',
              assetSummary: null,
              applyFuelSurcharge: false,
              applyEnhancedSafetyFee: false,
              applyEEC: false,
            },
            quantity: 2,
            listPrice: 0,
            floorPrice: 0,
            unitCost: null,
            netPrice: 0,
            customerPrice: 0,
            salesTaxAmount: null,
            productType: 'Bundle',
            ussNetAmount: 0,
            chargeType: 'Recurring',
            startDate: '2024-09-18',
            endDate: '2049-12-31',
            priceBookId: '01u3m00000O2tSBAAZ',
            productSubscriptionType: 'Renewable',
            subscriptionType: 'Renewable',
            productCode: '110-0000',
            aVASFCPQLocationCode: null,
            taxable: true,
            taxCode: null,
            tax: 0,
            quantityUnitOfMeasure: null,
            sortOrder: '00000000600000',
            effectiveStartDate: '2024-09-18',
            applyHoustonFranchiseFee: false,
            houstonFranchiseFeePerUnit: 0,
            houstonFranchiseFeesPercent: 0,
            houstonFranchiseAmount: 0,
            applyFuelSurcharge: false,
            fuelSurchargePercent: 0,
            fuelSurchargeAmount: 0,
            fuelSurchargePerUnit: 0,
            EECPercent: 0,
            EECAmount: 0,
            ESFPercent: 0,
            ESFAmount: 0,
          },
          {
            quoteLineId: 'a6KVA000000NjSh2AK',
            quoteId: 'a6OVA0000006Izx2AE',
            lineNumber: 11,
            name: 'QL-8397056',
            requiredBy: null,
            product: {
              id: '01t3m00000POgwyAAD',
              productCode: '113-3005',
              name: 'Pick Sani Standard',
              description: 'Pickup Sanitation - Standard',
              assetSummary: 'Cart-level P&D Sanitation',
              applyFuelSurcharge: true,
              applyEnhancedSafetyFee: true,
              applyEEC: true,
            },
            quantity: 1,
            listPrice: 0,
            floorPrice: 45,
            unitCost: null,
            netPrice: 0,
            customerPrice: 0,
            salesTaxAmount: 0,
            productType: 'P n D',
            ussNetAmount: 45,
            chargeType: 'One-Time',
            startDate: '2024-09-18',
            endDate: '2049-12-31',
            priceBookId: '01u3m00000O2tWOAAZ',
            productSubscriptionType: 'One-time',
            subscriptionType: 'One-time',
            productCode: '113-3005',
            aVASFCPQLocationCode: null,
            taxable: false,
            taxCode: 'FR010000',
            tax: 0,
            quantityUnitOfMeasure: 'Each',
            sortOrder: '50000000000000',
            effectiveStartDate: '2024-09-18',
            applyHoustonFranchiseFee: true,
            houstonFranchiseFeePerUnit: 0,
            houstonFranchiseFeesPercent: 0,
            houstonFranchiseAmount: 0,
            applyFuelSurcharge: true,
            fuelSurchargePercent: 14.9,
            fuelSurchargeAmount: 6.71,
            fuelSurchargePerUnit: 6.71,
            EECPercent: 10,
            EECAmount: 4.5,
            ESFPercent: 1,
            ESFAmount: 0.45,
          },
          {
            quoteLineId: 'a6KVA000000NjSi2AK',
            quoteId: 'a6OVA0000006Izx2AE',
            lineNumber: 12,
            name: 'QL-8397057',
            requiredBy: null,
            product: {
              id: '01t3m00000POgwjAAD',
              productCode: '113-3001',
              name: 'Del Sani Standard',
              description: 'Delivery Sanitation - Standard',
              assetSummary: 'Cart-level P&D Sanitation',
              applyFuelSurcharge: true,
              applyEnhancedSafetyFee: true,
              applyEEC: true,
            },
            quantity: 1,
            listPrice: 60,
            floorPrice: 45,
            unitCost: null,
            netPrice: 18207.62,
            customerPrice: 18207.62,
            salesTaxAmount: 0,
            productType: 'P n D',
            ussNetAmount: 45,
            chargeType: 'One-Time',
            startDate: '2024-09-18',
            endDate: '2049-12-31',
            priceBookId: '01u3m00000O2tXOAAZ',
            productSubscriptionType: 'One-time',
            subscriptionType: 'One-time',
            productCode: '113-3001',
            aVASFCPQLocationCode: null,
            taxable: false,
            taxCode: 'FR010000',
            tax: 0,
            quantityUnitOfMeasure: 'Each',
            sortOrder: '50000000000000',
            effectiveStartDate: '2024-09-18',
            applyHoustonFranchiseFee: true,
            houstonFranchiseFeePerUnit: 0,
            houstonFranchiseFeesPercent: 0,
            houstonFranchiseAmount: 0,
            applyFuelSurcharge: true,
            fuelSurchargePercent: 14.9,
            fuelSurchargeAmount: 6.71,
            fuelSurchargePerUnit: 6.71,
            EECPercent: 10,
            EECAmount: 4.5,
            ESFPercent: 1,
            ESFAmount: 0.45,
          },
          {
            quoteLineId: 'a6KVA000000NjSj2AK',
            quoteId: 'a6OVA0000006Izx2AE',
            lineNumber: 2,
            name: 'QL-8397058',
            requiredBy: 'a6KVA000000NjSf2AK',
            product: {
              id: '01t3m00000NTiuFAAT',
              productCode: '121-1102',
              name: '2 Stn Hand Sink',
              description: '2 Station Hand Wash Sink',
              assetSummary: '2 Station Hand Cleaning',
              applyFuelSurcharge: false,
              applyEnhancedSafetyFee: false,
              applyEEC: true,
            },
            quantity: 1,
            listPrice: 20,
            floorPrice: 40,
            unitCost: null,
            netPrice: 6069.21,
            customerPrice: 6069.21,
            salesTaxAmount: 3.12,
            productType: 'Asset',
            ussNetAmount: 40,
            chargeType: 'Recurring',
            startDate: '2024-09-18',
            endDate: '2049-12-31',
            priceBookId: '01u3m00000O2tTSAAZ',
            productSubscriptionType: 'Renewable',
            subscriptionType: 'Renewable',
            productCode: '121-1102',
            aVASFCPQLocationCode: null,
            taxable: true,
            taxCode: 'SANIRENT',
            tax: 2.5,
            quantityUnitOfMeasure: 'Each',
            sortOrder: '00000000200010',
            effectiveStartDate: '2024-09-18',
            applyHoustonFranchiseFee: true,
            houstonFranchiseFeePerUnit: 0,
            houstonFranchiseFeesPercent: 0,
            houstonFranchiseAmount: 0,
            applyFuelSurcharge: true,
            fuelSurchargePercent: 14.9,
            fuelSurchargeAmount: 5.96,
            fuelSurchargePerUnit: 5.96,
            EECPercent: 10,
            EECAmount: 4,
            ESFPercent: 0,
            ESFAmount: 0,
          },
          {
            quoteLineId: 'a6KVA000000NjSk2AK',
            quoteId: 'a6OVA0000006Izx2AE',
            lineNumber: 3,
            name: 'QL-8397059',
            requiredBy: 'a6KVA000000NjSf2AK',
            product: {
              id: '01t3m00000POgyQAAT',
              productCode: '122-2002',
              name: '1 Svc 2 Days Wk',
              description: '1 Service 2 Days per Week',
              assetSummary: 'Group A Sanitation',
              applyFuelSurcharge: true,
              applyEnhancedSafetyFee: true,
              applyEEC: true,
            },
            quantity: 1,
            listPrice: 160,
            floorPrice: 314,
            unitCost: null,
            netPrice: 48553.64,
            customerPrice: 48553.64,
            salesTaxAmount: 0,
            productType: 'Service',
            ussNetAmount: 370,
            chargeType: 'Recurring',
            startDate: '2024-09-18',
            endDate: '2049-12-31',
            priceBookId: '01u3m00000O2tYVAAZ',
            productSubscriptionType: 'Renewable',
            subscriptionType: 'Renewable',
            productCode: '122-2002',
            aVASFCPQLocationCode: null,
            taxable: false,
            taxCode: 'SANISERV',
            tax: 0,
            quantityUnitOfMeasure: 'Each',
            sortOrder: '00000000300020',
            effectiveStartDate: '2024-09-18',
            applyHoustonFranchiseFee: true,
            houstonFranchiseFeePerUnit: 0,
            houstonFranchiseFeesPercent: 0,
            houstonFranchiseAmount: 0,
            applyFuelSurcharge: true,
            fuelSurchargePercent: 14.9,
            fuelSurchargeAmount: 55.13,
            fuelSurchargePerUnit: 55.13,
            EECPercent: 10,
            EECAmount: 37,
            ESFPercent: 1,
            ESFAmount: 3.7,
          },
          {
            quoteLineId: 'a6KVA000000NjSl2AK',
            quoteId: 'a6OVA0000006Izx2AE',
            lineNumber: 4,
            name: 'QL-8397060',
            requiredBy: 'a6KVA000000NjSf2AK',
            product: {
              id: '01t3m00000POh0HAAT',
              productCode: '123-3009',
              name: 'Del Hand per Unit',
              description: 'Delivery Hand Cleaning - Per Unit Charge',
              assetSummary: 'Non-fees Sanitation',
              applyFuelSurcharge: true,
              applyEnhancedSafetyFee: true,
              applyEEC: true,
            },
            quantity: 1,
            listPrice: 5,
            floorPrice: 15,
            unitCost: null,
            netPrice: 1517.3,
            customerPrice: 1517.3,
            salesTaxAmount: 0,
            productType: 'P n D',
            ussNetAmount: 15,
            chargeType: 'One-Time',
            startDate: '2024-09-18',
            endDate: '2049-12-31',
            priceBookId: '01u3m00000O2tWWAAZ',
            productSubscriptionType: 'One-time',
            subscriptionType: 'One-time',
            productCode: '123-3009',
            aVASFCPQLocationCode: null,
            taxable: false,
            taxCode: 'FR010000',
            tax: 0,
            quantityUnitOfMeasure: 'Each',
            sortOrder: '00000000400001',
            effectiveStartDate: '2024-09-18',
            applyHoustonFranchiseFee: true,
            houstonFranchiseFeePerUnit: 0,
            houstonFranchiseFeesPercent: 0,
            houstonFranchiseAmount: 0,
            applyFuelSurcharge: true,
            fuelSurchargePercent: 14.9,
            fuelSurchargeAmount: 2.24,
            fuelSurchargePerUnit: 2.24,
            EECPercent: 10,
            EECAmount: 1.5,
            ESFPercent: 1,
            ESFAmount: 0.15,
          },
          {
            quoteLineId: 'a6KVA000000NjSm2AK',
            quoteId: 'a6OVA0000006Izx2AE',
            lineNumber: 5,
            name: 'QL-8397061',
            requiredBy: 'a6KVA000000NjSf2AK',
            product: {
              id: '01t3m00000POh0MAAT',
              productCode: '123-3010',
              name: 'Pick Hand per Unit',
              description: 'Pickup Hand Cleaning - Per Unit Charge',
              assetSummary: 'Non-fees Sanitation',
              applyFuelSurcharge: true,
              applyEnhancedSafetyFee: true,
              applyEEC: true,
            },
            quantity: 1,
            listPrice: 5,
            floorPrice: 15,
            unitCost: null,
            netPrice: 1517.3,
            customerPrice: 1517.3,
            salesTaxAmount: 0,
            productType: 'P n D',
            ussNetAmount: 15,
            chargeType: 'One-Time',
            startDate: '2024-09-18',
            endDate: '2049-12-31',
            priceBookId: '01u3m00000O2tVKAAZ',
            productSubscriptionType: 'One-time',
            subscriptionType: 'One-time',
            productCode: '123-3010',
            aVASFCPQLocationCode: null,
            taxable: false,
            taxCode: 'FR010000',
            tax: 0,
            quantityUnitOfMeasure: 'Each',
            sortOrder: '00000000500001',
            effectiveStartDate: '2024-09-18',
            applyHoustonFranchiseFee: true,
            houstonFranchiseFeePerUnit: 0,
            houstonFranchiseFeesPercent: 0,
            houstonFranchiseAmount: 0,
            applyFuelSurcharge: true,
            fuelSurchargePercent: 14.9,
            fuelSurchargeAmount: 2.24,
            fuelSurchargePerUnit: 2.24,
            EECPercent: 10,
            EECAmount: 1.5,
            ESFPercent: 1,
            ESFAmount: 0.15,
          },
          {
            quoteLineId: 'a6KVA000000NjSn2AK',
            quoteId: 'a6OVA0000006Izx2AE',
            lineNumber: 7,
            name: 'QL-8397062',
            requiredBy: 'a6KVA000000NjSg2AK',
            product: {
              id: '01t3m00000NTiw6AAD',
              productCode: '111-1001',
              name: 'Std Rest',
              description: 'Standard Restroom',
              assetSummary: 'Standard Restroom',
              applyFuelSurcharge: false,
              applyEnhancedSafetyFee: false,
              applyEEC: true,
            },
            quantity: 2,
            listPrice: 20,
            floorPrice: 40,
            unitCost: null,
            netPrice: 6069.21,
            customerPrice: 6069.21,
            salesTaxAmount: 6.25,
            productType: 'Asset',
            ussNetAmount: 80,
            chargeType: 'Recurring',
            startDate: '2024-09-18',
            endDate: '2049-12-31',
            priceBookId: '01u3m00000O2tTvAAJ',
            productSubscriptionType: 'Renewable',
            subscriptionType: 'Renewable',
            productCode: '111-1001',
            aVASFCPQLocationCode: null,
            taxable: true,
            taxCode: 'SANIRENT',
            tax: 5,
            quantityUnitOfMeasure: 'Each',
            sortOrder: '00000000700010',
            effectiveStartDate: '2024-09-18',
            applyHoustonFranchiseFee: true,
            houstonFranchiseFeePerUnit: 0,
            houstonFranchiseFeesPercent: 0,
            houstonFranchiseAmount: 0,
            applyFuelSurcharge: true,
            fuelSurchargePercent: 14.9,
            fuelSurchargeAmount: 11.92,
            fuelSurchargePerUnit: 5.96,
            EECPercent: 10,
            EECAmount: 8,
            ESFPercent: 0,
            ESFAmount: 0,
          },
          {
            quoteLineId: 'a6KVA000000NjSo2AK',
            quoteId: 'a6OVA0000006Izx2AE',
            lineNumber: 8,
            name: 'QL-8397063',
            requiredBy: 'a6KVA000000NjSg2AK',
            product: {
              id: '01t3m00000POgudAAD',
              productCode: '112-2002',
              name: '1 Svc 2 Days Wk',
              description: '1 Service 2 Days per Week',
              assetSummary: 'Group A Sanitation',
              applyFuelSurcharge: true,
              applyEnhancedSafetyFee: true,
              applyEEC: true,
            },
            quantity: 2,
            listPrice: 160,
            floorPrice: 298,
            unitCost: null,
            netPrice: 48553.64,
            customerPrice: 48553.64,
            salesTaxAmount: 0,
            productType: 'Service',
            ussNetAmount: 702,
            chargeType: 'Recurring',
            startDate: '2024-09-18',
            endDate: '2049-12-31',
            priceBookId: '01u3m00000O2tYTAAZ',
            productSubscriptionType: 'Renewable',
            subscriptionType: 'Renewable',
            productCode: '112-2002',
            aVASFCPQLocationCode: null,
            taxable: false,
            taxCode: 'TOILETSERV',
            tax: 0,
            quantityUnitOfMeasure: 'Each',
            sortOrder: '00000000800020',
            effectiveStartDate: '2024-09-18',
            applyHoustonFranchiseFee: true,
            houstonFranchiseFeePerUnit: 0,
            houstonFranchiseFeesPercent: 0,
            houstonFranchiseAmount: 0,
            applyFuelSurcharge: true,
            fuelSurchargePercent: 14.9,
            fuelSurchargeAmount: 104.6,
            fuelSurchargePerUnit: 52.3,
            EECPercent: 10,
            EECAmount: 70.2,
            ESFPercent: 1,
            ESFAmount: 7.02,
          },
          {
            quoteLineId: 'a6KVA000000NjSp2AK',
            quoteId: 'a6OVA0000006Izx2AE',
            lineNumber: 9,
            name: 'QL-8397064',
            requiredBy: 'a6KVA000000NjSg2AK',
            product: {
              id: '01t3m00000POgxIAAT',
              productCode: '113-3009',
              name: 'Del Rest per Unit',
              description: 'Delivery Restroom - Per Unit Charge',
              assetSummary: 'Non-fees Sanitation',
              applyFuelSurcharge: true,
              applyEnhancedSafetyFee: true,
              applyEEC: true,
            },
            quantity: 2,
            listPrice: 5,
            floorPrice: 15,
            unitCost: null,
            netPrice: 1517.3,
            customerPrice: 1517.3,
            salesTaxAmount: 0,
            productType: 'P n D',
            ussNetAmount: 30,
            chargeType: 'One-Time',
            startDate: '2024-09-18',
            endDate: '2049-12-31',
            priceBookId: '01u3m00000O2tVpAAJ',
            productSubscriptionType: 'One-time',
            subscriptionType: 'One-time',
            productCode: '113-3009',
            aVASFCPQLocationCode: null,
            taxable: false,
            taxCode: 'FR010000',
            tax: 0,
            quantityUnitOfMeasure: 'Each',
            sortOrder: '00000000900010',
            effectiveStartDate: '2024-09-18',
            applyHoustonFranchiseFee: true,
            houstonFranchiseFeePerUnit: 0,
            houstonFranchiseFeesPercent: 0,
            houstonFranchiseAmount: 0,
            applyFuelSurcharge: true,
            fuelSurchargePercent: 14.9,
            fuelSurchargeAmount: 4.48,
            fuelSurchargePerUnit: 2.24,
            EECPercent: 10,
            EECAmount: 3,
            ESFPercent: 1,
            ESFAmount: 0.3,
          },
          {
            quoteLineId: 'a6KVA000000NjSq2AK',
            quoteId: 'a6OVA0000006Izx2AE',
            lineNumber: 10,
            name: 'QL-8397065',
            requiredBy: 'a6KVA000000NjSg2AK',
            product: {
              id: '01t3m00000POgxNAAT',
              productCode: '113-3010',
              name: 'Pick Rest per Unit',
              description: 'Pickup Restroom - Per Unit Charge',
              assetSummary: 'Non-fees Sanitation',
              applyFuelSurcharge: true,
              applyEnhancedSafetyFee: true,
              applyEEC: true,
            },
            quantity: 2,
            listPrice: 5,
            floorPrice: 15,
            unitCost: null,
            netPrice: 1517.3,
            customerPrice: 1517.3,
            salesTaxAmount: 0,
            productType: 'P n D',
            ussNetAmount: 30,
            chargeType: 'One-Time',
            startDate: '2024-09-18',
            endDate: '2049-12-31',
            priceBookId: '01u3m00000O2tWPAAZ',
            productSubscriptionType: 'One-time',
            subscriptionType: 'One-time',
            productCode: '113-3010',
            aVASFCPQLocationCode: null,
            taxable: false,
            taxCode: 'FR010000',
            tax: 0,
            quantityUnitOfMeasure: 'Each',
            sortOrder: '00000001000010',
            effectiveStartDate: '2024-09-18',
            applyHoustonFranchiseFee: true,
            houstonFranchiseFeePerUnit: 0,
            houstonFranchiseFeesPercent: 0,
            houstonFranchiseAmount: 0,
            applyFuelSurcharge: true,
            fuelSurchargePercent: 14.9,
            fuelSurchargeAmount: 4.48,
            fuelSurchargePerUnit: 2.24,
            EECPercent: 10,
            EECAmount: 3,
            ESFPercent: 1,
            ESFAmount: 0.3,
          },
        ],
        sourceSystem: 'SalesForce',
        projectDetails: null,
        estimatedEndDate: '2024-10-23',
        createdDate: '2024-08-22T11:52:14.000+0000',
      },
    },
  };

  let getQuoteDetailsFailResponse = {
    status: 1006,
    message: 'Fail',
    data: {},
  };

  let firestoreResponse = {
    accountId: '0018I00000jIg0sQAC',
    isAutoPay: true,
    paymentMethodId: 'pm_1OMscFKX1Bgoxru0DjzyYC43',
    quoteId: 'a6O8I000000HGfXUAW',
  };



  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      controllers: [QuoteV2Controller],
      providers: [
        {
          provide: QuoteServiceV2,
          useValue: mockQuoteServiceV2,
        },
        {
          provide: SfdcQuoteService,
          useValue: mockSfdcQuoteService,
        },
        {
          provide: FirestoreService,
          useValue: mockFirestoreService,
        },
        {
          provide: CacheService,
          useValue: mockCacheService,
        },
        {
          provide: LoggerService,
          useValue: mockLoggerService,
        },
        {
          provide: UserService,
          useValue: mockUserService,
        },
        {
          provide: QuoteService,
          useValue: mockQuoteService,
        },
        {
          provide: AccountsService,
          useValue: mockAccountsService,
        },
      ],
    }).compile();

    controller = module.get<QuoteV2Controller>(QuoteV2Controller);
  });

  it('Should be defined', () => {
    expect(controller).toBeDefined();
  });

  // Get quote details
  it('Should return Quote Details', async () => {
    mockSfdcQuoteService.getQuoteDetailsById.mockResolvedValue(getSfdcQuoteDetailsResponse);
    mockFirestoreService.getDocument.mockResolvedValue(firestoreResponse);
    mockQuoteService.getQuoteHtmlModel.mockResolvedValue(getQuoteDetailsSuccessResponse);
    mockQuoteServiceV2.getQuoteDetailsById.mockResolvedValue(getQuoteDetailsSuccessResponse)

    const result = await controller.getQuote('a6OVA0000006Izx2AE');
    expect(result.message).toMatch('Success');
    expect(result.data.quoteModel).toHaveProperty('quoteId');
    // expect(result.data.quoteModel).toHaveProperty('lineItems');
    expect(result.data.quoteModel).toHaveProperty('jobSites');
    // expect(result.data.quoteModel).toHaveProperty('siteContact');
    expect(result.data.quoteModel).toHaveProperty('shippingAddress');
    expect(result.data.quoteModel).toHaveProperty('primaryContact');
    expect(result.data.quoteModel).toHaveProperty('ussContact');
    expect(result.data.quoteModel).toHaveProperty('purchaseOrder');
  });

  // it('Should return failed', async () => {
  //   mockSfdcQuoteService.getQuoteDetailsById('a6OVA0000006Izx2AE').mockResolvedValue(getSfdcQuoteDetailsResponse);
  //   mockFirestoreService.getDocument.mockResolvedValue(firestoreResponse);
  //   mockQuoteService.getQuoteHtmlModel.mockResolvedValue(getQuoteDetailsFailResponse);
  //   mockQuoteServiceV2.getQuoteDetailsById.mockResolvedValue(getQuoteDetailsSuccessResponse)


  //   const result = await controller.getQuote('');
  //   expect(result.message).toMatch('Fail');
  //   expect(result.status).toBe(1006);
  // });
});
